"""C2PA / AI-provenance marker vocabulary shared by every image format module.

Marker tables ported from the researched watermarks-remover project
(image_meta.py). Infrastructure layer: pure byte-matching helpers.
"""

from __future__ import annotations

from reasoner.core.ports.watermark_port import MarkFinding
from reasoner.domain.watermark.marks import MarkConfidence

# Chunk types / content patterns associated with C2PA / AI provenance.
C2PA_MARKERS: tuple[bytes, ...] = (
    b"c2pa",
    b"C2PA",
    b"jumb",
    b"JUMB",
    b"c2ma",
    b"contentcredentials",
    b"contentauth",
    b"cai:",
    b"http://ns.adobe.com/xmp/InstanceID/",  # not solely C2PA
)

AI_META_HINTS: tuple[bytes, ...] = (
    b"c2pa",
    b"C2PA",
    b"contentcredentials",
    b"ContentCredentials",
    b"digitalSourceType",
    b"trainedAlgorithmicMedia",
    b"compositeWithTrainedAlgorithmicMedia",
    b"algorithmicMedia",
    b"AIGC",
    b"aigc",
    b"AI generated",
    b"Generated by",
    b"Claude",
    b"Anthropic",
    b"OpenAI",
    b"SynthID",
    b"dcterms:provenance",
)


def contains_any(blob: bytes, needles: tuple[bytes, ...]) -> list[str]:
    """Return the subset of *needles* present in *blob* (case-insensitive)."""
    lower = blob.lower()
    found: list[str] = []
    for needle in needles:
        if needle.lower() in lower:
            found.append(needle.decode("ascii", errors="replace"))
    return found


def is_confirmed_c2pa_hit(hits: list[str]) -> bool:
    """True if any hit names a structural C2PA/JUMBF marker, not a soft hint."""
    return any(h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth") for h in hits)


def finding(description: str, confidence: MarkConfidence) -> MarkFinding:
    return MarkFinding(description=description, confidence=confidence)


__all__ = [
    "C2PA_MARKERS",
    "AI_META_HINTS",
    "contains_any",
    "is_confirmed_c2pa_hit",
    "finding",
]
