/**
 * AUTO-GENERATED by scripts/update_mindmap_meta.py on 2026-08-28 — do not edit
 * by hand. Regenerated on every commit from live registry, preset, and phase
 * counts (see tests/test_site_capabilities_sync.py) so marketing copy can
 * never state a capability number the code doesn't back.
 */

export const CAPABILITIES = {
  methods: 31,
  presets: 49,
  directModels: 178,
  routableModels: 420,
  providerAdapters: 8,
  testFiles: 244,
  generatedAt: '2026-08-28',
} as const;

/** Display names for the direct (non-OpenRouter) fallback provider adapters. */
export const PROVIDERS = ['Anthropic', 'OpenAI', 'Google', 'Mistral', 'DeepSeek', 'xAI', 'Perplexity', 'Qwen'] as const;

/**
 * PROVIDERS plus a curated set of additional labs notable enough to name on
 * the landing page marquee even though they route only through OpenRouter,
 * not through a direct fallback adapter — see _CURATED_MARQUEE_LABS in
 * scripts/update_mindmap_meta.py. Each is still gated on having a live model
 * in the registry, so this can shrink but never carries a lab with nothing
 * behind it.
 */
export const MARQUEE_LABS = ['Anthropic', 'OpenAI', 'Google', 'Mistral', 'DeepSeek', 'xAI', 'Perplexity', 'Qwen', 'Moonshot AI', 'Meta', 'Zhipu AI', 'MiniMax'] as const;

/**
 * Sycophancy controls that are actually present in the code, per commit.
 * See docs/SYCOPHANCY_MITIGATION.md and docs/plans/sycophancy-mitigation.md.
 * A control renders true only when its detector finds the mechanism at the
 * place it is used, not merely defined — landing-page copy must be gated on
 * these, never hand-written past them.
 */
export const SYCOPHANCY_CONTROLS = {
  noApprovalGradient: true,
  mandatoryDissent: true,
  confidencePenalty: true,
  noStyleSelector: true,
  directPathEpistemicRules: true,
  premiseAudit: true,
  deaffirmEgress: false,
  advisoryRoute: false,
  revisionLicence: true,
  verificationStep: false,
} as const;
