/**
 * AUTO-GENERATED by scripts/update_mindmap_meta.py on 2026-08-19 — do not edit
 * by hand. Regenerated on every commit from live registry, preset, and phase
 * counts (see tests/test_site_capabilities_sync.py) so marketing copy can
 * never state a capability number the code doesn't back.
 */

export const CAPABILITIES = {
  methods: 31,
  presets: 50,
  directModels: 180,
  routableModels: 448,
  providerAdapters: 8,
  testFiles: 237,
  generatedAt: '2026-08-19',
} as const;

/** Display names for the direct (non-OpenRouter) fallback provider adapters. */
export const PROVIDERS = ['Anthropic', 'OpenAI', 'Google', 'Mistral', 'DeepSeek', 'xAI', 'Perplexity', 'Qwen'] as const;
