"""The agent tool schema is a published contract; pin it like one.

An agent registers these definitions verbatim at startup, so a rename or a
quietly widened input surface is a breaking change for every caller -- not a
refactor. The snapshot makes that visible in review.

Refresh with::

    UPDATE_SDK_CONTRACT=1 python -m pytest tests/test_agent_tools_contract.py
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from reasoner.api.schemas import RunRequest
from reasoner.application.services.tool_schema import (
    AGENT_FIELDS,
    as_anthropic,
    as_openai,
    build_tool_definitions,
)

pytestmark = pytest.mark.unit

CONTRACT = Path(__file__).resolve().parents[1] / "sdk" / "contract" / "tools.json"
_UPDATE = os.environ.get("UPDATE_SDK_CONTRACT") == "1"


def _definitions():
    return build_tool_definitions(RunRequest.model_json_schema())


def _payload() -> dict:
    return {
        "$comment": (
            "Generated by tests/test_agent_tools_contract.py. Do not hand-edit. "
            "Refresh with UPDATE_SDK_CONTRACT=1 pytest tests/test_agent_tools_contract.py."
        ),
        "tools": as_anthropic(_definitions()),
    }


def test_tool_schema_matches_the_committed_contract():
    current = _payload()
    if _UPDATE:
        CONTRACT.write_text(json.dumps(current, indent=2) + "\n", encoding="utf-8")
        pytest.skip("Contract snapshot refreshed")

    assert CONTRACT.exists(), f"Missing {CONTRACT}; regenerate with UPDATE_SDK_CONTRACT=1"
    assert json.loads(CONTRACT.read_text(encoding="utf-8")) == current


def test_every_exposed_field_exists_on_the_request_model():
    """The allowlist is a projection, not a parallel schema."""
    properties = RunRequest.model_json_schema()["properties"]
    assert set(AGENT_FIELDS) <= set(properties)


def test_nothing_outside_the_allowlist_leaks_into_a_tool():
    """A field added to RunRequest must not become agent-settable by default."""
    for definition in _definitions():
        assert set(definition.input_schema["properties"]) <= set(AGENT_FIELDS)
        assert definition.input_schema["additionalProperties"] is False


def test_problem_is_the_only_required_input():
    run = next(d for d in _definitions() if d.name == "reasoner_run_sync")
    assert run.input_schema["required"] == ["problem"]


def test_read_only_tools_are_marked_and_the_run_tools_are_not():
    by_name = {d.name: d for d in _definitions()}
    assert by_name["reasoner_gate"].read_only
    assert by_name["reasoner_estimate"].read_only
    assert by_name["reasoner_presets"].read_only
    assert not by_name["reasoner_run"].read_only
    assert not by_name["reasoner_run_sync"].read_only


def test_descriptions_tell_the_model_what_the_call_costs():
    """A tool description is the only prompt the calling model reads."""
    run = next(d for d in _definitions() if d.name == "reasoner_run_sync")
    assert "20-90 seconds" in run.description
    assert "costs" in run.description.lower()


def test_openai_projection_carries_the_same_tools_and_schemas():
    anthropic = as_anthropic(_definitions())
    openai = as_openai(_definitions())

    assert [t["name"] for t in anthropic] == [t["function"]["name"] for t in openai]
    assert [t["input_schema"] for t in anthropic] == [t["function"]["parameters"] for t in openai]
    assert all(t["type"] == "function" for t in openai)
