"""
Regression tests for backend bug fixes.

Each test reproduces the original bug (would fail without the patch)
and verifies the fix (passes with the patch).

Bugs covered:
- BUG-005: CSRF token generation/verification secret mismatch
- BUG-014: Race condition in PostgresQuotaRepository._get_pool()
- BUG-015: Race condition in PostgresSubscriptionRepository._get_pool()
- BUG-016: Cache load failure permanently disables disk cache
- BUG-018: HTTP 200 on internal server errors in pipeline routes
"""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import json
import os
import secrets
import tempfile
import time
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest


# ──────────────────────────────────────────────────────────────────────────────
# BUG-005: CSRF token generation/verification secret mismatch
# ──────────────────────────────────────────────────────────────────────────────

class TestCsrfSecretConsistency:
    """Verify that generate_csrf_token and verify_csrf_token use the SAME secret."""

    @pytest.fixture(autouse=True)
    def _ensure_csrf_secret(self, monkeypatch):
        """Ensure CSRF_SECRET is set for all tests in this class.

        The settings object is built once at import, so setting the env var alone
        does not change settings.CSRF_SECRET — patch the attribute the module reads.
        """
        from reasoner.core.settings import settings

        monkeypatch.setenv("CSRF_SECRET", "test-csrf-secret-do-not-reuse")
        monkeypatch.setattr(settings, "CSRF_SECRET", "test-csrf-secret-do-not-reuse")

    def test_generate_and_verify_use_same_secret(self, monkeypatch):
        """A token generated by generate_csrf_token must be verifiable by verify_csrf_token."""
        # Force re-import with the new env var
        import importlib
        from reasoner.api import csrf as csrf_module

        importlib.reload(csrf_module)

        token = csrf_module.generate_csrf_token()
        signed = csrf_module.sign_csrf_token(token)
        assert csrf_module.verify_csrf_token(signed) is True

    def test_signed_token_roundtrip(self, monkeypatch):
        """generate_signed_csrf_token → verify_csrf_token must succeed."""
        import importlib
        from reasoner.api import csrf as csrf_module

        importlib.reload(csrf_module)

        signed = csrf_module.generate_signed_csrf_token()
        assert csrf_module.verify_csrf_token(signed) is True

    def test_tampered_token_fails(self, monkeypatch):
        """Tampering with the token should cause verification to fail."""
        import importlib
        from reasoner.api import csrf as csrf_module

        importlib.reload(csrf_module)

        signed = csrf_module.generate_signed_csrf_token()
        tampered = signed[:-4] + "XXXX"
        assert csrf_module.verify_csrf_token(tampered) is False

    def test_expired_token_fails(self, monkeypatch):
        """A token with a past expiry should fail verification."""
        import importlib
        from reasoner.api import csrf as csrf_module

        importlib.reload(csrf_module)

        # Manually create an expired token
        expiry = int(time.time()) - 10  # 10 seconds ago
        nonce = secrets.token_urlsafe(16)
        payload = f"{expiry}:{nonce}"
        sig = hmac.new(
            csrf_module._CSRF_SECRET, payload.encode(), hashlib.sha256
        ).hexdigest()[:16]
        expired_token = f"{payload}:{sig}"
        signed = csrf_module.sign_csrf_token(expired_token)
        assert csrf_module.verify_csrf_token(signed) is False


# ──────────────────────────────────────────────────────────────────────────────
# BUG-014: Race condition in PostgresQuotaRepository._get_pool()
# ──────────────────────────────────────────────────────────────────────────────

class TestQuotaRepoPoolRaceCondition:
    """Verify that concurrent calls to _get_pool() create only ONE asyncpg pool."""

    @pytest.mark.asyncio
    async def test_concurrent_get_pool_creates_single_pool(self, monkeypatch):
        """Multiple concurrent _get_pool() calls must result in exactly one create_pool."""
        from reasoner.infrastructure.persistence.quota_repo_postgres import PostgresQuotaRepository

        call_count = 0

        async def mock_create_pool(*args, **kwargs):
            nonlocal call_count
            call_count += 1
            # Simulate async work to widen the race window
            await asyncio.sleep(0.01)
            return MagicMock()

        monkeypatch.setattr("asyncpg.create_pool", mock_create_pool)

        repo = PostgresQuotaRepository("postgresql://test", pool_size=2)

        # Fire 10 concurrent _get_pool() calls
        await asyncio.gather(*[repo._get_pool() for _ in range(10)])

        assert call_count == 1, f"Expected 1 pool creation, got {call_count}"

    @pytest.mark.asyncio
    async def test_sequential_get_pool_reuses_pool(self, monkeypatch):
        """Sequential calls must reuse the existing pool."""
        from reasoner.infrastructure.persistence.quota_repo_postgres import PostgresQuotaRepository

        call_count = 0

        async def mock_create_pool(*args, **kwargs):
            nonlocal call_count
            call_count += 1
            return MagicMock()

        monkeypatch.setattr("asyncpg.create_pool", mock_create_pool)
        # _pool is a class attribute; an earlier test may have left one behind.
        monkeypatch.setattr(PostgresQuotaRepository, "_pool", None)

        repo = PostgresQuotaRepository("postgresql://test", pool_size=2)

        await repo._get_pool()
        await repo._get_pool()
        await repo._get_pool()

        assert call_count == 1


# ──────────────────────────────────────────────────────────────────────────────
# BUG-015: Race condition in PostgresSubscriptionRepository._get_pool()
# ──────────────────────────────────────────────────────────────────────────────

class TestSubscriptionRepoPoolRaceCondition:
    """Verify that concurrent calls to _get_pool() create only ONE asyncpg pool."""

    @pytest.mark.asyncio
    async def test_concurrent_get_pool_creates_single_pool(self, monkeypatch):
        """Multiple concurrent _get_pool() calls must result in exactly one create_pool."""
        from reasoner.infrastructure.persistence.subscription_repo import PostgresSubscriptionRepository

        call_count = 0

        async def mock_create_pool(*args, **kwargs):
            nonlocal call_count
            call_count += 1
            await asyncio.sleep(0.01)
            return MagicMock()

        monkeypatch.setattr("asyncpg.create_pool", mock_create_pool)

        repo = PostgresSubscriptionRepository("postgresql://test", pool_size=2)

        await asyncio.gather(*[repo._get_pool() for _ in range(10)])

        assert call_count == 1, f"Expected 1 pool creation, got {call_count}"


# ──────────────────────────────────────────────────────────────────────────────
# BUG-016: Cache load failure permanently disables disk cache
# ──────────────────────────────────────────────────────────────────────────────

class TestTokenCacheLoadFailure:
    """Verify that a failed disk load does NOT permanently disable the cache."""

    @pytest.mark.asyncio
    async def test_load_failure_allows_retry(self, tmp_path, monkeypatch):
        """If _load_from_disk fails, _loaded should remain False so the next call retries."""
        from reasoner.token_cache import TokenAwareCache

        cache = TokenAwareCache(cache_dir=tmp_path)
        load_attempts = 0

        async def failing_load():
            nonlocal load_attempts
            load_attempts += 1
            raise OSError("Simulated disk I/O error")

        monkeypatch.setattr(cache, "_load_from_disk", failing_load)

        # The failure is swallowed — a corrupt cache file must not fail the request —
        # but the cache must not be marked loaded, or it never re-reads from disk.
        await cache._ensure_loaded()

        assert cache._loaded is False, "_loaded must remain False after failed load"
        assert load_attempts == 1

        # Second call should ALSO attempt load (retry behavior)
        await cache._ensure_loaded()

        assert load_attempts == 2, "Second call should retry load, not skip it"

        # Retries are capped so a permanently unreadable cache stops retrying.
        for _ in range(5):
            await cache._ensure_loaded()
        assert load_attempts == cache._MAX_LOAD_ATTEMPTS

    @pytest.mark.asyncio
    async def test_successful_load_sets_loaded_true(self, tmp_path):
        """A successful load should set _loaded = True."""
        from reasoner.token_cache import TokenAwareCache

        cache = TokenAwareCache(cache_dir=tmp_path)
        await cache._ensure_loaded()
        assert cache._loaded is True

    @pytest.mark.asyncio
    async def test_corrupted_file_then_recovery(self, tmp_path, monkeypatch):
        """A corrupted cache file should not permanently disable the cache."""
        from reasoner.token_cache import TokenAwareCache

        # Create a corrupted JSON file
        bad_file = tmp_path / "bad.json"
        bad_file.write_text("NOT JSON")

        cache = TokenAwareCache(cache_dir=tmp_path)

        # First load should handle the corrupted file gracefully
        await cache._ensure_loaded()
        assert cache._loaded is True

        # The corrupted file should have been removed
        assert not bad_file.exists()


# ──────────────────────────────────────────────────────────────────────────────
# BUG-018: HTTP 200 on internal server errors in pipeline routes
# ──────────────────────────────────────────────────────────────────────────────

class TestPipelineRoutesReturnProperStatusCodes:
    """Verify that pipeline routes raise HTTPException(500) instead of returning 200 with error JSON."""

    @pytest.fixture
    def mock_user(self):
        from reasoner.domain.saas import User
        from uuid import uuid4

        return User(
            id=uuid4(),
            email="test@example.com",
            display_name="Test User",
            scopes=["read"],
        )

    @pytest.mark.asyncio
    async def test_get_event_stats_raises_500_on_error(self, mock_user, monkeypatch):
        """get_event_stats must raise HTTPException(500) on internal errors, not return 200."""
        from fastapi import HTTPException
        from reasoner.api.routes.pipelines import get_event_stats

        def broken_get_components():
            raise RuntimeError("Simulated internal error")

        monkeypatch.setattr(
            "reasoner.api.get_architecture_components",
            broken_get_components,
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_event_stats(user=mock_user)

        assert exc_info.value.status_code == 500
        assert "Internal server error" in exc_info.value.detail

    @pytest.mark.asyncio
    async def test_list_pipelines_raises_500_on_error(self, mock_user, monkeypatch):
        """list_pipelines must raise HTTPException(500) on internal errors."""
        from fastapi import HTTPException
        from reasoner.api.routes.pipelines import list_pipelines

        def broken_get_components():
            raise RuntimeError("Simulated internal error")

        monkeypatch.setattr(
            "reasoner.api.get_architecture_components",
            broken_get_components,
        )

        with pytest.raises(HTTPException) as exc_info:
            await list_pipelines(user=mock_user)

        assert exc_info.value.status_code == 500

    @pytest.mark.asyncio
    async def test_get_pipeline_status_raises_500_on_error(self, mock_user, monkeypatch):
        """get_pipeline_status must raise HTTPException(500) on internal errors."""
        from fastapi import HTTPException
        from reasoner.api.routes.pipelines import get_pipeline_status

        def broken_get_components():
            raise RuntimeError("Simulated internal error")

        monkeypatch.setattr(
            "reasoner.api.get_architecture_components",
            broken_get_components,
        )
        # Routes now check pipeline ownership first; grant it so the error path is reached.
        monkeypatch.setattr(
            "reasoner.api.routes.pipelines._check_pipeline_ownership",
            AsyncMock(return_value=True),
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_pipeline_status(pipeline_id="test-pipe", user=mock_user)

        assert exc_info.value.status_code == 500

    @pytest.mark.asyncio
    async def test_delete_pipeline_raises_500_on_error(self, mock_user, monkeypatch):
        """delete_pipeline must raise HTTPException(500) on internal errors."""
        from fastapi import HTTPException
        from reasoner.api.routes.pipelines import delete_pipeline

        def broken_get_components():
            raise RuntimeError("Simulated internal error")

        monkeypatch.setattr(
            "reasoner.api.get_architecture_components",
            broken_get_components,
        )
        # Routes now check pipeline ownership first; grant it so the error path is reached.
        monkeypatch.setattr(
            "reasoner.api.routes.pipelines._check_pipeline_ownership",
            AsyncMock(return_value=True),
        )

        with pytest.raises(HTTPException) as exc_info:
            await delete_pipeline(pipeline_id="test-pipe", user=mock_user, csrf_checked=None)

        assert exc_info.value.status_code == 500

    @pytest.mark.asyncio
    async def test_resume_pipeline_raises_500_on_error(self, mock_user, monkeypatch):
        """resume_pipeline must raise HTTPException(500) on internal errors."""
        from fastapi import HTTPException
        from reasoner.api.routes.pipelines import resume_pipeline

        def broken_get_components():
            raise RuntimeError("Simulated internal error")

        monkeypatch.setattr(
            "reasoner.api.get_architecture_components",
            broken_get_components,
        )
        # Routes now check pipeline ownership first; grant it so the error path is reached.
        monkeypatch.setattr(
            "reasoner.api.routes.pipelines._check_pipeline_ownership",
            AsyncMock(return_value=True),
        )

        with pytest.raises(HTTPException) as exc_info:
            await resume_pipeline(pipeline_id="test-pipe", user=mock_user, csrf_checked=None)

        assert exc_info.value.status_code == 500
