# AUTO-GENERATED by Self-Healing Codebase Prompt v1.0
# Phase: 1.1 — Codebase Introspection Engine
# Generated: 2026-03-25
# Purpose: Map entire codebase for targeted healing
# Human review required: NO (P2/P3 only)
# DO NOT EDIT — regenerate with: python healing/introspection_engine.py

"""
Codebase Introspection Engine

Analyzes the entire Reasoner codebase to generate:
1. Function Inventory with complexity scores
2. Dependency Graph (internal + external)
3. Dead Code Map
4. Type Coverage Map
5. Error Handling Map

Output: introspection_report.json + introspection_report.md
"""

from __future__ import annotations

import ast
import json
import logging
import os
import sys
from collections import defaultdict
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from enum import Enum
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


class Severity(str, Enum):
    """Severity levels for introspection findings."""
    P0 = "P0"  # CRITICAL - Healing blocker
    P1 = "P1"  # HIGH - Generate fix, flag for review
    P2 = "P2"  # MEDIUM - Generate fix, auto-apply if tests pass
    P3 = "P3"  # LOW - Log and schedule


class ComplexityLevel(str, Enum):
    """Complexity scoring levels."""
    LOW = "LOW"       # 1-5
    MEDIUM = "MEDIUM" # 6-10
    HIGH = "HIGH"     # 11-15
    CRITICAL = "CRITICAL"  # >15


@dataclass
class FunctionInfo:
    """Information about a single function/method."""
    id: str
    name: str
    module: str
    file_path: str
    line_number: int
    inputs: list[str] = field(default_factory=list)
    outputs: list[str] = field(default_factory=list)
    side_effects: list[str] = field(default_factory=list)
    has_tests: bool = False
    coverage_percent: float = 0.0
    complexity_score: int = 1
    complexity_level: ComplexityLevel = ComplexityLevel.LOW
    severity: Severity = Severity.P3
    has_docstring: bool = False
    has_type_annotations: bool = False
    has_error_handling: bool = False
    is_public: bool = True
    is_async: bool = False
    decorators: list[str] = field(default_factory=list)
    calls_external: list[str] = field(default_factory=list)
    bare_except_count: int = 0


@dataclass
class ModuleInfo:
    """Information about a module."""
    name: str
    file_path: str
    functions: list[str] = field(default_factory=list)
    classes: list[str] = field(default_factory=list)
    imports_internal: list[str] = field(default_factory=list)
    imports_external: list[str] = field(default_factory=list)
    has_tests: bool = False
    is_dead_code: bool = False


@dataclass
class DependencyEdge:
    """Edge in dependency graph."""
    source: str
    target: str
    dependency_type: str  # "internal" or "external"
    import_statement: str = ""


@dataclass
class DeadCodeItem:
    """Dead code item."""
    item_type: str  # "function", "class", "module", "import"
    name: str
    file_path: str
    line_number: int
    reason: str
    severity: Severity = Severity.P3
    auto_fix_available: bool = True


@dataclass
class TypeCoverageGap:
    """Type annotation gap."""
    item_type: str
    name: str
    file_path: str
    missing_annotations: list[str] = field(default_factory=list)
    has_any_type: bool = False
    severity: Severity = Severity.P2


@dataclass
class ErrorHandlingGap:
    """Error handling gap."""
    function_name: str
    file_path: str
    line_number: int
    gap_type: str  # "no_handling", "bare_except", "missing_return_validation"
    severity: Severity = Severity.P1
    recommendation: str = ""


@dataclass
class IntrospectionReport:
    """Complete introspection report."""
    timestamp: str
    project_root: str
    total_modules: int
    total_functions: int
    total_classes: int
    functions: list[FunctionInfo] = field(default_factory=list)
    modules: list[ModuleInfo] = field(default_factory=list)
    dependency_graph: list[DependencyEdge] = field(default_factory=list)
    dead_code: list[DeadCodeItem] = field(default_factory=list)
    type_gaps: list[TypeCoverageGap] = field(default_factory=list)
    error_gaps: list[ErrorHandlingGap] = field(default_factory=list)
    circular_dependencies: list[list[str]] = field(default_factory=list)
    complexity_summary: dict[str, int] = field(default_factory=dict)
    coverage_summary: dict[str, Any] = field(default_factory=dict)
    severity_summary: dict[str, int] = field(default_factory=dict)


class CodebaseIntrospector:
    """
    Main introspector class.
    
    Scans the codebase and generates comprehensive reports.
    """

    def __init__(self, project_root: str, test_dirs: list[str] | None = None):
        self.project_root = Path(project_root)
        self.test_dirs = test_dirs or ["tests", "test_*"]
        self.functions: dict[str, FunctionInfo] = {}
        self.modules: dict[str, ModuleInfo] = {}
        self.imports_internal: dict[str, set[str]] = defaultdict(set)
        self.imports_external: dict[str, set[str]] = defaultdict(set)
        self.test_coverage: dict[str, float] = {}
        self.dead_code: list[DeadCodeItem] = []
        self.type_gaps: list[TypeCoverageGap] = []
        self.error_gaps: list[ErrorHandlingGap] = []

    def scan(self) -> IntrospectionReport:
        """
        Perform complete codebase scan.
        
        Returns:
            IntrospectionReport with all findings
        """
        logger.info(f"Starting introspection of {self.project_root}")

        # Step 1: Discover all Python modules
        logger.info("Step 1: Discovering Python modules...")
        python_files = self._discover_python_files()
        logger.info(f"  Found {len(python_files)} Python files")

        # Step 2: Parse each module
        logger.info("Step 2: Parsing modules...")
        for file_path in python_files:
            self._parse_module(file_path)
        logger.info(f"  Parsed {len(self.modules)} modules")

        # Step 3: Map test coverage
        logger.info("Step 3: Mapping test coverage...")
        self._map_test_coverage()

        # Step 4: Build dependency graph
        logger.info("Step 4: Building dependency graph...")
        dependency_edges = self._build_dependency_graph()

        # Step 5: Detect circular dependencies
        logger.info("Step 5: Detecting circular dependencies...")
        circular_deps = self._detect_circular_dependencies()
        if circular_deps:
            logger.warning(f"  Found {len(circular_deps)} circular dependencies")

        # Step 6: Identify dead code
        logger.info("Step 6: Identifying dead code...")
        self._identify_dead_code()

        # Step 7: Map type coverage gaps
        logger.info("Step 7: Mapping type coverage gaps...")
        self._map_type_gaps()

        # Step 8: Map error handling gaps
        logger.info("Step 8: Mapping error handling gaps...")
        self._map_error_gaps()

        # Step 9: Calculate complexity scores
        logger.info("Step 9: Calculating complexity scores...")
        self._calculate_complexity()

        # Step 10: Generate report
        logger.info("Step 10: Generating report...")
        return self._generate_report(dependency_edges, circular_deps)

    def _discover_python_files(self) -> list[Path]:
        """Discover all Python files in project."""
        python_files = []
        exclude_dirs = {
            '__pycache__', '.pytest_cache', '.git', '.venv',
            'venv', 'node_modules', '.claude', 'cache', 'uploads',
            '.worktrees'
        }

        for root, dirs, files in os.walk(self.project_root):
            # Exclude certain directories
            dirs[:] = [d for d in dirs if d not in exclude_dirs]

            for file in files:
                if file.endswith('.py'):
                    file_path = Path(root) / file
                    # Skip test files for function inventory
                    if not any(part.startswith('test_') for part in file_path.parts):
                        python_files.append(file_path)

        return python_files

    def _parse_module(self, file_path: Path) -> None:
        """Parse a single Python module."""
        try:
            with open(file_path, encoding='utf-8') as f:
                source = f.read()

            tree = ast.parse(source, filename=str(file_path))
            relative_path = file_path.relative_to(self.project_root)
            module_name = str(relative_path.with_suffix('')).replace(os.sep, '.')

            # Create module info
            module_info = ModuleInfo(
                name=module_name,
                file_path=str(relative_path),
            )

            # Extract imports
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if alias.name.startswith('reasoner') or alias.name.startswith('core'):
                            module_info.imports_internal.append(alias.name)
                            self.imports_internal[module_name].add(alias.name)
                        else:
                            module_info.imports_external.append(alias.name)
                            self.imports_external[module_name].add(alias.name)
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        if node.module.startswith('reasoner') or node.module.startswith('core'):
                            module_info.imports_internal.append(node.module)
                            self.imports_internal[module_name].add(node.module)
                        else:
                            module_info.imports_external.append(node.module)
                            self.imports_external[module_name].add(node.module)

            # Extract functions and classes
            for node in tree.body:
                if isinstance(node, ast.FunctionDef) or isinstance(node, ast.AsyncFunctionDef):
                    func_info = self._extract_function_info(node, file_path, module_name)
                    self.functions[func_info.id] = func_info
                    module_info.functions.append(func_info.id)

                elif isinstance(node, ast.ClassDef):
                    module_info.classes.append(node.name)
                    # Extract methods
                    for item in node.body:
                        if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                            method_info = self._extract_function_info(
                                item, file_path, module_name, class_name=node.name
                            )
                            self.functions[method_info.id] = method_info
                            module_info.functions.append(method_info.id)

            self.modules[module_name] = module_info

        except Exception as e:
            logger.error(f"Failed to parse {file_path}: {e}")

    def _extract_function_info(
        self,
        node: ast.AST,
        file_path: Path,
        module_name: str,
        class_name: str | None = None
    ) -> FunctionInfo:
        """Extract function information from AST node."""
        name = node.name
        func_id = f"{module_name}.{class_name}.{name}" if class_name else f"{module_name}.{name}"
        relative_path = file_path.relative_to(self.project_root)

        # Extract inputs (arguments)
        inputs = []
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for arg in node.args.args:
                inputs.append(arg.arg)

        # Check for docstring
        has_docstring = (
            isinstance(node.body[0], ast.Expr) and
            isinstance(node.body[0].value, ast.Constant) and
            isinstance(node.body[0].value.value, str)
        ) if node.body else False

        # Check for type annotations
        has_type_annotations = all(
            arg.annotation is not None
            for arg in node.args.args
            if arg.arg != 'self' and arg.arg != 'cls'
        ) if node.args else True

        # Check for error handling
        has_error_handling = False
        bare_except_count = 0
        calls_external = []

        for child in ast.walk(node):
            if isinstance(child, ast.Try):
                has_error_handling = True
            elif isinstance(child, ast.ExceptHandler):
                if child.type is None:
                    bare_except_count += 1
            elif isinstance(child, ast.Call):
                # Track external calls
                if isinstance(child.func, ast.Attribute):
                    calls_external.append(child.func.attr)
                elif isinstance(child.func, ast.Name):
                    calls_external.append(child.func.id)

        # Determine if public
        is_public = not name.startswith('_')

        # Get decorators
        decorators = []
        for decorator in node.decorator_list:
            if isinstance(decorator, ast.Name):
                decorators.append(decorator.id)
            elif isinstance(decorator, ast.Attribute):
                decorators.append(decorator.attr)

        return FunctionInfo(
            id=func_id,
            name=name,
            module=module_name,
            file_path=str(relative_path),
            line_number=node.lineno or 0,
            inputs=inputs,
            has_docstring=has_docstring,
            has_type_annotations=has_type_annotations,
            has_error_handling=has_error_handling,
            is_public=is_public,
            is_async=isinstance(node, ast.AsyncFunctionDef),
            decorators=decorators,
            calls_external=list(set(calls_external))[:10],  # Limit to 10
            bare_except_count=bare_except_count,
        )

    def _map_test_coverage(self) -> None:
        """Map test coverage to functions."""
        # Simple heuristic: check if test file exists for module
        for _module_name, module_info in self.modules.items():
            # Check if corresponding test file exists
            test_file_name = f"test_{module_info.file_path.replace(os.sep, '_').replace('.py', '')}.py"
            test_file = self.project_root / test_file_name

            # Also check tests/ directory
            test_file_alt = self.project_root / "tests" / f"test_{Path(module_info.file_path).stem}.py"

            has_test = test_file.exists() or test_file_alt.exists()
            module_info.has_tests = has_test

            # Update functions in this module
            for func_id in module_info.functions:
                if func_id in self.functions:
                    self.functions[func_id].has_tests = has_test
                    # Estimate coverage (crude heuristic)
                    if has_test:
                        self.functions[func_id].coverage_percent = 50.0  # Assume 50% if test exists
                    self.test_coverage[func_id] = self.functions[func_id].coverage_percent

    def _build_dependency_graph(self) -> list[DependencyEdge]:
        """Build dependency graph from imports."""
        edges = []

        for module_name, imports in self.imports_internal.items():
            for imp in imports:
                edges.append(DependencyEdge(
                    source=module_name,
                    target=imp,
                    dependency_type="internal",
                ))

        for module_name, imports in self.imports_external.items():
            for imp in imports:
                edges.append(DependencyEdge(
                    source=module_name,
                    target=imp,
                    dependency_type="external",
                ))

        return edges

    def _detect_circular_dependencies(self) -> list[list[str]]:
        """Detect circular dependencies using DFS."""
        circular = []
        visited = set()
        rec_stack = set()
        path = []

        def dfs(module_name: str) -> None:
            visited.add(module_name)
            rec_stack.add(module_name)
            path.append(module_name)

            for dep in self.imports_internal.get(module_name, set()):
                if dep not in visited:
                    dfs(dep)
                elif dep in rec_stack:
                    # Found cycle
                    cycle_start = path.index(dep)
                    cycle = path[cycle_start:] + [dep]
                    circular.append(cycle)

            path.pop()
            rec_stack.remove(module_name)

        for module_name in self.modules:
            if module_name not in visited:
                dfs(module_name)

        return circular

    def _identify_dead_code(self) -> None:
        """Identify potentially dead code."""
        called_functions = set()

        # Collect all function calls across codebase
        for func_info in self.functions.values():
            called_functions.update(func_info.calls_external)

        # Check for uncalled public functions
        for func_info in self.functions.values():
            if func_info.is_public and func_info.name not in called_functions:
                # Check if it's an entry point (main, app, etc.)
                if func_info.name in ['main', 'app', 'create_app', 'run']:
                    continue

                self.dead_code.append(DeadCodeItem(
                    item_type="function",
                    name=func_info.name,
                    file_path=func_info.file_path,
                    line_number=func_info.line_number,
                    reason="Public function not called anywhere in codebase",
                    severity=Severity.P3,
                    auto_fix_available=False,  # Requires human review
                ))

        # Check for unused imports
        for _module_name, module_info in self.modules.items():
            for imp in module_info.imports_external:
                # Simple check: if import name not used in any function
                if imp not in called_functions:
                    self.dead_code.append(DeadCodeItem(
                        item_type="import",
                        name=imp,
                        file_path=module_info.file_path,
                        line_number=0,
                        reason=f"Import '{imp}' may be unused",
                        severity=Severity.P3,
                        auto_fix_available=True,
                    ))

    def _map_type_gaps(self) -> None:
        """Map type annotation gaps."""
        for func_info in self.functions.values():
            if not func_info.has_type_annotations and func_info.is_public:
                self.type_gaps.append(TypeCoverageGap(
                    item_type="function",
                    name=func_info.name,
                    file_path=func_info.file_path,
                    missing_annotations=func_info.inputs,
                    severity=Severity.P2 if func_info.complexity_score > 5 else Severity.P3,
                ))

    def _map_error_gaps(self) -> None:
        """Map error handling gaps."""
        for func_info in self.functions.values():
            # Check for bare except
            if func_info.bare_except_count > 0:
                self.error_gaps.append(ErrorHandlingGap(
                    function_name=func_info.name,
                    file_path=func_info.file_path,
                    line_number=func_info.line_number,
                    gap_type="bare_except",
                    severity=Severity.P1,
                    recommendation="Replace bare 'except:' with specific exception types",
                ))

            # Check for I/O operations without error handling
            io_keywords = ['open', 'read', 'write', 'request', 'query', 'execute']
            has_io = any(io in func_info.calls_external for io in io_keywords)

            if has_io and not func_info.has_error_handling and func_info.is_public:
                self.error_gaps.append(ErrorHandlingGap(
                    function_name=func_info.name,
                    file_path=func_info.file_path,
                    line_number=func_info.line_number,
                    gap_type="no_handling",
                    severity=Severity.P1,
                    recommendation="Add try/except block around I/O operations",
                ))

    def _calculate_complexity(self) -> None:
        """Calculate complexity scores for all functions."""
        for func_info in self.functions.values():
            # Simple complexity based on:
            # - Number of lines (estimated)
            # - Number of branches (if/elif/else/for/while)
            # - Number of function calls

            # Base complexity
            complexity = 1

            # Add for inputs
            complexity += len(func_info.inputs) * 0.5

            # Add for external calls
            complexity += len(func_info.calls_external) * 0.3

            # Adjust for async (more complex)
            if func_info.is_async:
                complexity += 1

            # Round and cap
            complexity = min(20, int(complexity))
            func_info.complexity_score = complexity

            # Determine level
            if complexity <= 5:
                func_info.complexity_level = ComplexityLevel.LOW
                func_info.severity = Severity.P3
            elif complexity <= 10:
                func_info.complexity_level = ComplexityLevel.MEDIUM
                func_info.severity = Severity.P2
            elif complexity <= 15:
                func_info.complexity_level = ComplexityLevel.HIGH
                func_info.severity = Severity.P1
            else:
                func_info.complexity_level = ComplexityLevel.CRITICAL
                func_info.severity = Severity.P0

    def _generate_report(
        self,
        dependency_edges: list[DependencyEdge],
        circular_deps: list[list[str]]
    ) -> IntrospectionReport:
        """Generate final introspection report."""
        # Calculate summaries
        complexity_summary = {
            "LOW": sum(1 for f in self.functions.values() if f.complexity_level == ComplexityLevel.LOW),
            "MEDIUM": sum(1 for f in self.functions.values() if f.complexity_level == ComplexityLevel.MEDIUM),
            "HIGH": sum(1 for f in self.functions.values() if f.complexity_level == ComplexityLevel.HIGH),
            "CRITICAL": sum(1 for f in self.functions.values() if f.complexity_level == ComplexityLevel.CRITICAL),
        }

        severity_summary = {
            "P0": sum(1 for f in self.functions.values() if f.severity == Severity.P0),
            "P1": len([g for g in self.error_gaps if g.severity == Severity.P1]),
            "P2": len(self.type_gaps),
            "P3": len(self.dead_code),
        }

        coverage_summary = {
            "total_functions": len(self.functions),
            "tested_functions": sum(1 for f in self.functions.values() if f.has_tests),
            "average_coverage": sum(f.coverage_percent for f in self.functions.values()) / max(1, len(self.functions)),
        }

        return IntrospectionReport(
            timestamp=datetime.now(UTC).isoformat(),
            project_root=str(self.project_root),
            total_modules=len(self.modules),
            total_functions=len(self.functions),
            total_classes=sum(len(m.classes) for m in self.modules.values()),
            functions=list(self.functions.values()),
            modules=list(self.modules.values()),
            dependency_graph=dependency_edges,
            dead_code=self.dead_code,
            type_gaps=self.type_gaps,
            error_gaps=self.error_gaps,
            circular_dependencies=circular_deps,
            complexity_summary=complexity_summary,
            coverage_summary=coverage_summary,
            severity_summary=severity_summary,
        )


def generate_markdown_report(report: IntrospectionReport) -> str:
    """Generate Markdown report from IntrospectionReport."""
    md = []
    md.append("# Codebase Introspection Report")
    md.append(f"\n**Generated:** {report.timestamp}\n")

    md.append("## Summary\n")
    md.append(f"- **Total Modules:** {report.total_modules}")
    md.append(f"- **Total Functions:** {report.total_functions}")
    md.append(f"- **Total Classes:** {report.total_classes}")
    md.append(f"- **Average Coverage:** {report.coverage_summary['average_coverage']:.1f}%\n")

    md.append("## Complexity Distribution\n")
    for level, count in report.complexity_summary.items():
        md.append(f"- **{level}:** {count}")
    md.append("")

    md.append("## Severity Summary\n")
    for severity, count in report.severity_summary.items():
        if count > 0:
            md.append(f"- **{severity}:** {count}")
    md.append("")

    # Critical functions (P0)
    critical_funcs = [f for f in report.functions if f.severity == Severity.P0]
    if critical_funcs:
        md.append("## ⚠️ P0 - CRITICAL Functions (Complexity > 15)\n")
        md.append("| Function | Module | Complexity |")
        md.append("|----------|--------|------------|")
        for func in critical_funcs[:10]:
            md.append(f"| {func.name} | {func.module} | {func.complexity_score} |")
        md.append("")

    # Error handling gaps
    if report.error_gaps:
        md.append("## Error Handling Gaps\n")
        md.append(f"**Total Gaps:** {len(report.error_gaps)}\n")
        md.append("### Top 20 Gaps\n")
        md.append("| Function | File | Gap Type | Recommendation |")
        md.append("|----------|------|----------|----------------|")
        for gap in report.error_gaps[:20]:
            md.append(f"| {gap.function_name} | {gap.file_path} | {gap.gap_type} | {gap.recommendation} |")
        md.append("")

    # Type gaps
    if report.type_gaps:
        md.append("## Type Annotation Gaps\n")
        md.append(f"**Total Gaps:** {len(report.type_gaps)}\n")
        md.append("### Top 20 Gaps\n")
        md.append("| Function | File | Missing Annotations |")
        md.append("|----------|------|---------------------|")
        for gap in report.type_gaps[:20]:
            missing = ", ".join(gap.missing_annotations) if gap.missing_annotations else "All"
            md.append(f"| {gap.name} | {gap.file_path} | {missing} |")
        md.append("")

    # Dead code
    if report.dead_code:
        md.append("## Dead Code\n")
        md.append(f"**Total Items:** {len(report.dead_code)}\n")
        md.append("### Top 20 Items\n")
        md.append("| Type | Name | File | Reason |")
        md.append("|------|------|------|--------|")
        for item in report.dead_code[:20]:
            md.append(f"| {item.item_type} | {item.name} | {item.file_path} | {item.reason} |")
        md.append("")

    # Circular dependencies
    if report.circular_dependencies:
        md.append("## Circular Dependencies\n")
        md.append(f"**Total Cycles:** {len(report.circular_dependencies)}\n")
        for i, cycle in enumerate(report.circular_dependencies, 1):
            md.append(f"{i}. {' → '.join(cycle)}")
        md.append("")

    return "\n".join(md)


def main():
    """Main entry point."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    # Determine project root
    project_root = Path(__file__).parent.parent

    # Run introspection
    introspector = CodebaseIntrospector(str(project_root))
    report = introspector.scan()

    # Save JSON report
    json_path = project_root / "healing" / "introspection_report.json"
    json_path.parent.mkdir(exist_ok=True)

    # Convert to dict for JSON serialization
    report_dict = {
        "timestamp": report.timestamp,
        "project_root": report.project_root,
        "total_modules": report.total_modules,
        "total_functions": report.total_functions,
        "total_classes": report.total_classes,
        "functions": [asdict(f) for f in report.functions],
        "modules": [asdict(m) for m in report.modules],
        "dependency_graph": [asdict(e) for e in report.dependency_graph],
        "dead_code": [asdict(d) for d in report.dead_code],
        "type_gaps": [asdict(t) for t in report.type_gaps],
        "error_gaps": [asdict(e) for e in report.error_gaps],
        "circular_dependencies": report.circular_dependencies,
        "complexity_summary": report.complexity_summary,
        "coverage_summary": report.coverage_summary,
        "severity_summary": report.severity_summary,
    }

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(report_dict, f, indent=2)
    logger.info(f"JSON report saved to {json_path}")

    # Save Markdown report
    md_report = generate_markdown_report(report)
    md_path = project_root / "healing" / "introspection_report.md"
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(md_report)
    logger.info(f"Markdown report saved to {md_path}")

    # Print summary
    print("\n" + "="*80)
    print("INTROSPECTION COMPLETE")
    print("="*80)
    print(f"Modules: {report.total_modules}")
    print(f"Functions: {report.total_functions}")
    print(f"Average Coverage: {report.coverage_summary['average_coverage']:.1f}%")
    print(f"P0 Issues: {report.severity_summary['P0']}")
    print(f"P1 Issues: {report.severity_summary['P1']}")
    print(f"P2 Issues: {report.severity_summary['P2']}")
    print(f"P3 Issues: {report.severity_summary['P3']}")
    print("="*80)

    # SELF-VERIFICATION BLOCK
    # This block verifies the introspection engine itself
    print("\nSELF-VERIFICATION:")
    try:
        import ast
        with open(__file__, encoding='utf-8') as f:
            source = f.read()
        ast.parse(source)  # Syntax check
        print("[OK] Syntax valid")

        # Check all functions are discoverable
        tree = ast.parse(source)
        functions = [n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]
        assert len(functions) > 0, "No functions found"
        print(f"[OK] {len(functions)} functions discoverable")

        # Verify report was generated
        assert json_path.exists(), "JSON report not generated"
        print("[OK] JSON report generated")

        assert md_path.exists(), "Markdown report not generated"
        print("[OK] Markdown report generated")

        print("\n[PASS] ALL SELF-VERIFICATION CHECKS PASSED")

    except Exception as e:
        print(f"\n[FAIL] SELF-VERIFICATION FAILED: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
