# AUTO-GENERATED by Self-Healing Codebase Prompt v1.0
# Phase: 1.2 — Autonomous Test Generation
# Generated: 2026-03-25
# Coverage target: I/O error handling gaps (19 P1 issues from introspection)
# Human review required: YES (P1 error handling tests)
# DO NOT EDIT — regenerate with: python healing/test_generation_engine.py

"""
Autonomous Test Generation Engine

Generates comprehensive tests for untested or under-tested paths.
Priority order:
1. Functions with coverage = 0% AND complexity > 5
2. Functions on critical paths (I/O, auth, payments)
3. Functions handling external I/O
4. All remaining untested functions

Each test includes:
- Happy path test
- Boundary test
- Adversarial test
- Regression anchor (if applicable)
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────
# TEST TEMPLATES
# ─────────────────────────────────────────────────────────────────────

IO_ERROR_HANDLING_TEST_TEMPLATE = '''
# AUTO-GENERATED by Self-Healing Codebase Prompt v1.0
# Phase: 1.2 - Autonomous Test Generation
# Generated: {timestamp}
# Coverage target: {function_name} (I/O error handling gap - P1)
# Human review required: YES (P1 error handling)
# DO NOT EDIT - regenerate with: python healing/test_generation_engine.py

"""
Auto-generated tests for {function_name}

Tests cover:
1. Happy path - valid I/O operations
2. Boundary - file not found, permission errors
3. Adversarial - path traversal, invalid paths
4. Regression - error handling that was missing
"""

import pytest
import asyncio
import tempfile
import os
from pathlib import Path
from unittest.mock import patch, MagicMock, AsyncMock

# Import the function under test
from {module_path} import {function_name}


class Test{class_name}:
    """Test suite for {function_name}"""

    # -----------------------------------------------------------------
    # Happy Path Tests
    # -----------------------------------------------------------------

    def test_{function_name}_happy_path(self):
        """Test {function_name} with valid inputs and successful I/O""" 
        # Test implementation depends on function signature
        # This is a placeholder - actual implementation requires manual review
        pytest.skip("Manual implementation required - review function signature")

    {async_test}test_{function_name}_successful_operation(self):    
        """Test successful I/O operation"""
        pytest.skip("Manual implementation required")

    # -----------------------------------------------------------------
    # Boundary Tests
    # -----------------------------------------------------------------

    def test_{function_name}_file_not_found(self):
        """Test handling of FileNotFoundError"""
        with pytest.raises(FileNotFoundError):
            # Mock the I/O operation to raise FileNotFoundError
            with patch('{module_path}.open', side_effect=FileNotFoundError("File not found")):
                {function_call}

    def test_{function_name}_permission_error(self):
        """Test handling of PermissionError"""
        with pytest.raises(PermissionError):
            with patch('{module_path}.open', side_effect=PermissionError("Permission denied")):
                {function_call}

    def test_{function_name}_empty_input(self):
        """Test handling of empty input"""
        pytest.skip("Manual implementation required - define empty input case")

    def test_{function_name}_none_input(self):
        """Test handling of None input"""
        with pytest.raises((TypeError, ValueError)):
            {function_name}(None)

    # -----------------------------------------------------------------
    # Adversarial Tests
    # -----------------------------------------------------------------

    def test_{function_name}_path_traversal_attempt(self):
        """Test that path traversal attempts are rejected"""
        malicious_path = "../../../etc/passwd"
        with pytest.raises((ValueError, OSError)):
            {function_name}(malicious_path)

    def test_{function_name}_oversized_input(self):
        """Test handling of oversized input"""
        large_input = "x" * 1000000  # 1MB string
        with pytest.raises((MemoryError, ValueError)):
            {function_name}(large_input)

    def test_{function_name}_concurrent_access(self):
        """Test concurrent access handling"""
        import threading

        errors = []

        def concurrent_call():
            try:
                {function_call}
            except Exception as e:
                errors.append(e)

        threads = [threading.Thread(target=concurrent_call) for _ in range(10)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        # Should not have race condition errors
        assert len(errors) == 0

    # -----------------------------------------------------------------
    # Regression Anchor
    # -----------------------------------------------------------------

    def test_{function_name}_error_handling_regression(self):
        """
        REGRESSION: P1 error handling gap from introspection report     

        This test ensures error handling was added after being flagged  
        as missing in the Phase 1.1 introspection.
        """
        # Verify the function has try/except blocks
        import inspect
        try:
            source = inspect.getsource({function_name})
            # Check for error handling patterns
            has_try = "try:" in source
            has_except = "except" in source

            # This assertion will fail until error handling is added
            assert has_try and has_except, (
                f"{function_name} lacks proper error handling. "
                "Add try/except blocks around I/O operations."
            )
        except Exception:
            pytest.skip("Could not inspect source")

    # -----------------------------------------------------------------
    # Self-Verification Block
    # -----------------------------------------------------------------

    def test_self_verification(self):
        """
        Verifies this test file is syntactically valid
        and all test functions are discoverable.
        """
        import ast
        source = open(__file__, encoding='utf-8').read()
        tree = ast.parse(source)  # syntax check

        test_fns = [
            n.name for n in ast.walk(tree)
            if isinstance(n, ast.FunctionDef) and n.name.startswith("test_")
        ]

        assert len(test_fns) > 1, "No tests generated"
        assert "test_self_verification" in test_fns, "Self-verification test missing"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''

# ─────────────────────────────────────────────────────────────────────
# TEST GENERATION ENGINE
# ─────────────────────────────────────────────────────────────────────

class TestGenerationEngine:
    """
    Autonomous test generation engine.
    
    Reads introspection report and generates targeted tests.
    """

    def __init__(self, project_root: str, introspection_report_path: str):
        self.project_root = Path(project_root)
        self.introspection_report_path = Path(introspection_report_path)
        self.generated_tests: list[dict[str, Any]] = []

    def load_introspection_report(self) -> dict[str, Any]:
        """Load introspection report JSON."""
        with open(self.introspection_report_path, encoding='utf-8') as f:
            return json.load(f)

    def generate_tests_for_error_gaps(self, error_gaps: list[dict[str, Any]]) -> None:
        """Generate tests for error handling gaps."""
        for gap in error_gaps:
            test_config = {
                "function_name": gap["function_name"],
                "file_path": gap["file_path"],
                "gap_type": gap["gap_type"],
                "severity": gap["severity"],
                "recommendation": gap["recommendation"],
            }

            # Generate test file content
            test_content = self._generate_io_error_test(test_config)

            # Determine test file path
            module_name = Path(gap["file_path"]).stem
            test_file_name = f"test_{module_name}_{gap['function_name']}_auto.py"
            test_file_path = self.project_root / "healing" / "generated_tests" / test_file_name

            self.generated_tests.append({
                "path": str(test_file_path),
                "function": gap["function_name"],
                "gap_type": gap["gap_type"],
            })

            # Write test file
            test_file_path.parent.mkdir(exist_ok=True, parents=True)
            with open(test_file_path, 'w', encoding='utf-8') as f:
                f.write(test_content)

            logger.info(f"Generated test for {gap['function_name']} → {test_file_path}")

    def _generate_io_error_test(self, config: dict[str, Any]) -> str:
        """Generate I/O error handling test."""
        # Ensure module path use dots instead of slashes/backslashes
        raw_path = Path(config["file_path"]).with_suffix('').as_posix()
        module_path = raw_path.replace('/', '.')
        function_name = config["function_name"]

        # Determine if async
        is_async = any(
            keyword in config["function_name"].lower()
            for keyword in ["async", "fetch", "load", "save", "get", "post"]
        )

        async_test = "@pytest.mark.asyncio\n    async def " if is_async else "def "
        function_call = f"await {function_name}('test_input')" if is_async else f"{function_name}('test_input')"

        # Class name from function name
        class_name = "".join(word.capitalize() for word in function_name.split("_"))

        return IO_ERROR_HANDLING_TEST_TEMPLATE.format(
            timestamp=datetime.now(UTC).isoformat(),
            function_name=function_name,
            module_path=module_path,
            class_name=class_name,
            async_test=async_test,
            function_call=function_call,
        )

    def generate_all_tests(self) -> None:
        """Generate all tests from introspection report."""
        report = self.load_introspection_report()

        logger.info(f"Generating tests for {len(report['error_gaps'])} error handling gaps...")
        self.generate_tests_for_error_gaps(report["error_gaps"])

        logger.info(f"Generated {len(self.generated_tests)} test files")

    def generate_summary(self) -> str:
        """Generate test generation summary."""
        summary = [
            "="*80,
            "TEST GENERATION SUMMARY",
            "="*80,
            f"Generated: {len(self.generated_tests)} test files",
            "",
            "Generated Tests:",
        ]

        for test in self.generated_tests:
            summary.append(f"  - {test['function']} ({test['gap_type']})")
            summary.append(f"    -> {test['path']}")

        summary.extend([
            "",
            "NEXT STEPS:",
            "1. Review generated tests (human review required for P1)",
            "2. Implement actual test logic (placeholders included)",
            "3. Run tests: pytest healing/generated_tests/ -v",
            "4. Fix any error handling issues discovered",
            "="*80,
        ])

        return "\n".join(summary)


def main():
    """Main entry point."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    # Repo root, not src/reasoner. This is used purely as an IO root -- to find
    # the introspection report and to write healing/generated_tests/ -- so
    # unlike introspection_engine.py it needs no separate scan target. Before
    # the src/ layout, parent.parent was the repo root; it now yields
    # src/reasoner, which put both under the source tree and left the
    # workflow's `path: healing/generated_tests/` upload empty.
    project_root = Path(__file__).resolve().parents[3]
    introspection_report = project_root / "healing" / "introspection_report.json"

    if not introspection_report.exists():
        logger.error("Introspection report not found. Run introspection_engine.py first.")
        return

    engine = TestGenerationEngine(str(project_root), str(introspection_report))
    engine.generate_all_tests()

    print(engine.generate_summary())

    # SELF-VERIFICATION BLOCK
    print("\nSELF-VERIFICATION:")
    try:
        import ast

        # Verify all generated test files are syntactically valid
        for test_info in engine.generated_tests:
            test_path = Path(test_info["path"])
            if test_path.exists():
                source = open(test_path, encoding='utf-8').read()
                ast.parse(source)  # Syntax check
                print(f"[OK] {test_info['function']}: Syntax valid")
            else:
                print(f"[FAIL] {test_info['function']}: File not found")

        print(f"\n[PASS] Generated {len(engine.generated_tests)} syntactically valid test files")

    except Exception as e:
        print(f"\n[FAIL] SELF-VERIFICATION FAILED: {e}")
        import sys
        sys.exit(1)


if __name__ == "__main__":
    main()
