# Backward-compatible shim — all content moved to reasoner.phases package
from reasoner.phases._universal import *
from reasoner.phases.analogical import *
from reasoner.phases.bayesian import *
from reasoner.phases.cove import *
from reasoner.phases.debate import *
from reasoner.phases.delphi import *
from reasoner.phases.dialectical import *
from reasoner.phases.jury import *
from reasoner.phases.multi_perspective import *
from reasoner.phases.pot import *
from reasoner.phases.pre_mortem import *
from reasoner.phases.research import *
from reasoner.phases.scientific import *
from reasoner.phases.self_discover import *
from reasoner.phases.socratic import *
from reasoner.phases.sot import *
from reasoner.phases.tot import *
from reasoner.phases.writing import *
