#!/usr/bin/env python3
"""Refresh the bundled OpenRouter model catalogue.

Fetches https://openrouter.ai/api/v1/models and writes a trimmed copy to
``src/reasoner/domain/openrouter_models.json``, which ``domain/pricing.py``
loads at import time to build ``PRICING_DB``.

The upstream payload is ~2 MB of provider metadata; only the fields the
application actually reads are kept, which brings the bundled file down to
roughly 150 KB so it can be committed and shipped in the Docker image.

Usage::

    python scripts/update_openrouter_catalogue.py            # refresh in place
    python scripts/update_openrouter_catalogue.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import httpx

MODELS_URL = "https://openrouter.ai/api/v1/models"
# The default listing returns text-output models only. Image generators
# (seedream, krea, qwen-image, grok-imagine, flux, recraft, riverflow ...) are a
# separate lane and are INVISIBLE unless this filter is passed. Several registry
# entries were deleted in the past as "provider gone from OpenRouter" purely
# because someone diffed against the default listing — always fetch both.
IMAGE_MODELS_URL = "https://openrouter.ai/api/v1/models?output_modalities=image"
OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "reasoner"
    / "domain"
    / "openrouter_models.json"
)
REQUEST_TIMEOUT = 60.0

# Fields kept from each upstream model entry. Everything else (per-provider
# endpoints, descriptions, moderation flags) is dropped.
#
# Pure image generators price per image rather than per token: they carry
# ``image``/``image_token``/``image_output`` and have no ``prompt``/``completion``
# at all. Keep those keys or the whole image lane silently prices at zero.
_KEPT_PRICING_KEYS = (
    "prompt", "completion", "request", "image", "image_token", "image_output",
)

# An entry is usable if it carries at least one of these, i.e. we can cost it.
_COSTABLE_KEYS = ("prompt", "completion", "image", "image_token", "image_output")


def _trim(entry: dict[str, Any]) -> dict[str, Any] | None:
    """Reduce one upstream model entry to the fields the app consumes."""
    model_id = entry.get("id")
    pricing = entry.get("pricing") or {}
    if not model_id or not any(k in pricing for k in _COSTABLE_KEYS):
        return None

    arch = entry.get("architecture") or {}
    trimmed: dict[str, Any] = {
        "id": model_id,
        "pricing": {k: pricing[k] for k in _KEPT_PRICING_KEYS if k in pricing},
        "context_length": entry.get("context_length"),
        "architecture": {
            "input_modalities": arch.get("input_modalities") or [],
            "output_modalities": arch.get("output_modalities") or [],
        },
        "supported_parameters": entry.get("supported_parameters") or [],
    }
    return trimmed


def fetch_catalogue() -> dict[str, Any]:
    """Fetch and trim the live OpenRouter catalogue (text lane + image lane)."""
    by_id: dict[str, dict[str, Any]] = {}
    for url in (MODELS_URL, IMAGE_MODELS_URL):
        response = httpx.get(url, timeout=REQUEST_TIMEOUT)
        response.raise_for_status()
        for entry in response.json().get("data", []):
            if trimmed := _trim(entry):
                # Text lane wins on overlap: hybrid models (gemini-*-image) appear
                # in both and the text-lane entry carries the token prices.
                by_id.setdefault(trimmed["id"], trimmed)

    models = sorted(by_id.values(), key=lambda m: m["id"])

    return {
        "_source": [MODELS_URL, IMAGE_MODELS_URL],
        "_fetched_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "_note": "Generated by scripts/update_openrouter_catalogue.py — do not edit by hand.",
        "data": models,
    }


def _model_ids(catalogue: dict[str, Any]) -> set[str]:
    return {m["id"] for m in catalogue.get("data", [])}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if the bundled catalogue differs from upstream.",
    )
    args = parser.parse_args()

    catalogue = fetch_catalogue()
    live_ids = _model_ids(catalogue)

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"MISSING: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        with OUTPUT_PATH.open("r", encoding="utf-8") as fh:
            bundled_ids = _model_ids(json.load(fh))
        added, removed = live_ids - bundled_ids, bundled_ids - live_ids
        if not added and not removed:
            print(f"up to date ({len(live_ids)} models)")
            return 0
        for mid in sorted(added):
            print(f"+ {mid}")
        for mid in sorted(removed):
            print(f"- {mid}")
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as fh:
        json.dump(catalogue, fh, indent=1, sort_keys=False)
        fh.write("\n")

    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"wrote {len(live_ids)} models to {OUTPUT_PATH} ({size_kb:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
