#!/usr/bin/env python3
"""Refresh the bundled OpenRouter model catalogue.

Fetches https://openrouter.ai/api/v1/models and writes a trimmed copy to
``src/reasoner/domain/openrouter_models.json``, which ``domain/pricing.py``
loads at import time to build ``PRICING_DB``.

The upstream payload is ~2 MB of provider metadata; only the fields the
application actually reads are kept, which brings the bundled file down to
roughly 150 KB so it can be committed and shipped in the Docker image.

Usage::

    python scripts/update_openrouter_catalogue.py            # refresh in place
    python scripts/update_openrouter_catalogue.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import httpx

MODELS_URL = "https://openrouter.ai/api/v1/models"
# The default listing returns text-output models only. Image generators
# (seedream, krea, qwen-image, grok-imagine, flux, recraft, riverflow ...) are a
# separate lane and are INVISIBLE unless this filter is passed. Several registry
# entries were deleted in the past as "provider gone from OpenRouter" purely
# because someone diffed against the default listing — always fetch both.
IMAGE_MODELS_URL = "https://openrouter.ai/api/v1/models?output_modalities=image"
OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "reasoner"
    / "domain"
    / "openrouter_models.json"
)
REQUEST_TIMEOUT = 60.0

# Fields kept from each upstream model entry. Everything else (per-provider
# endpoints, descriptions, moderation flags) is dropped.
#
# Pure image generators price per image rather than per token: they carry
# ``image``/``image_token``/``image_output`` and have no ``prompt``/``completion``
# at all. Keep those keys or the whole image lane silently prices at zero.
_KEPT_PRICING_KEYS = (
    "prompt", "completion", "request", "image", "image_token", "image_output",
)

# An entry is usable if it carries at least one of these, i.e. we can cost it.
_COSTABLE_KEYS = ("prompt", "completion", "image", "image_token", "image_output")


def _trim(entry: dict[str, Any]) -> dict[str, Any] | None:
    """Reduce one upstream model entry to the fields the app consumes."""
    model_id = entry.get("id")
    pricing = entry.get("pricing") or {}
    if not model_id or not any(k in pricing for k in _COSTABLE_KEYS):
        return None

    arch = entry.get("architecture") or {}
    trimmed: dict[str, Any] = {
        "id": model_id,
        "pricing": {k: pricing[k] for k in _KEPT_PRICING_KEYS if k in pricing},
        "context_length": entry.get("context_length"),
        "architecture": {
            "input_modalities": arch.get("input_modalities") or [],
            "output_modalities": arch.get("output_modalities") or [],
        },
        "supported_parameters": entry.get("supported_parameters") or [],
    }

    # Per-model reasoning capability: which effort levels the model actually
    # accepts, its default, and whether reasoning can be disabled. Upstream
    # omits the key entirely for non-reasoning models, so the absence is
    # meaningful and is preserved rather than defaulted to {}.
    #
    # Without this the gateway's per-phase effort was sent to every model
    # unconditionally: 54 routed models advertise a restricted list (e.g.
    # google/gemini-3.8-flash accepts only high/medium/low, while the
    # classification and fusion phases ask for "minimal"), so an unsupported
    # level was being sent on every such call. See
    # infrastructure/llm/reasoning_effort.py for the clamp this feeds.
    reasoning = entry.get("reasoning")
    if isinstance(reasoning, dict):
        trimmed["reasoning"] = reasoning

    return trimmed


def fetch_catalogue() -> dict[str, Any]:
    """Fetch and trim the live OpenRouter catalogue (text lane + image lane)."""
    by_id: dict[str, dict[str, Any]] = {}
    for url in (MODELS_URL, IMAGE_MODELS_URL):
        response = httpx.get(url, timeout=REQUEST_TIMEOUT)
        response.raise_for_status()
        for entry in response.json().get("data", []):
            if trimmed := _trim(entry):
                # Text lane wins on overlap: hybrid models (gemini-*-image) appear
                # in both and the text-lane entry carries the token prices.
                by_id.setdefault(trimmed["id"], trimmed)

    models = sorted(by_id.values(), key=lambda m: m["id"])

    return {
        "_source": [MODELS_URL, IMAGE_MODELS_URL],
        "_fetched_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "_note": "Generated by scripts/update_openrouter_catalogue.py — do not edit by hand.",
        "data": models,
    }


def _model_ids(catalogue: dict[str, Any]) -> set[str]:
    return {m["id"] for m in catalogue.get("data", [])}


ENDPOINTS_URL = "https://openrouter.ai/api/v1/models/{model_id}/endpoints"


def check_endpoints() -> int:
    """Report every registry-routed model with no healthy serving endpoint.

    Distinct from ``--check``, which compares model *ids* against
    /api/v1/models. A model can be listed there and still be unservable: on
    2026-09-06 ``nousresearch/hermes-4-70b`` was listed, its only endpoint was
    Nebius at ``status: -5``, and a live call returned

        404 {"error":{"message":"Provider returned error",
             "metadata":{"raw":"{\\"detail\\":\\"The model `NousResearch/Hermes-4-70B`
             does not exist\\"}"}}}

    It was multi-perspective-budget's destructive generator, so Phase 2 lost a
    perspective on every run of the default budget preset while the pipeline
    reported success.

    Ids absent from /api/v1/models 404 here, which catches the other half:
    seven ``~<vendor>/<family>-latest`` aliases that answered
    ``HTTP 400 ... is not a valid model ID`` on every call. No preset routed
    them, so the preset-scoped alias-honesty test could not see them either.

    Only a 404 fails the run. A negative endpoint ``status`` is reported as
    SUSPECT and does not, because the codes are undocumented and a negative one
    does not imply dead. Two were verified by live call on 2026-09-06:

        -5  nousresearch/hermes-4-70b (sole endpoint Nebius)  404, dead
        -2  nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free  200, "ok"

    Treating every negative status as fatal would have condemned a working
    model. Two data points are not a specification, so the negative-status
    branch prints and a human decides.

    Needs no API key. Costs one request per distinct served id (211 as of
    2026-09-06), so this belongs on the schedule, not on every PR.
    """
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
    os.environ.setdefault("CSRF_ENFORCE_BACKEND", "false")
    from reasoner.infrastructure.llm.registry import _REGISTRY

    served = sorted(
        {
            cfg["model"].lstrip("~")
            for cfg in _REGISTRY.values()
            if isinstance(cfg, dict) and "model" in cfg and "/" in cfg["model"]
        }
    )

    dead: list[tuple[str, str]] = []
    suspect: list[tuple[str, str]] = []
    with httpx.Client(timeout=REQUEST_TIMEOUT) as client:
        for model_id in served:
            try:
                response = client.get(ENDPOINTS_URL.format(model_id=model_id))
            except httpx.HTTPError as exc:  # network flake, not a verdict
                print(f"? {model_id}: {type(exc).__name__}: {exc}", file=sys.stderr)
                continue
            if response.status_code == 404:
                dead.append((model_id, "not in /api/v1/models (404)"))
                continue
            if response.status_code != 200:
                print(f"? {model_id}: HTTP {response.status_code}", file=sys.stderr)
                continue
            endpoints = response.json().get("data", {}).get("endpoints", [])
            if not endpoints:
                # Meta-routers (openrouter/*) legitimately list none and serve
                # fine, so an empty list is not evidence of death.
                continue
            if not any((e.get("status") or 0) >= 0 for e in endpoints):
                providers = ", ".join(
                    f"{e.get('provider_name')}={e.get('status')}" for e in endpoints
                )
                suspect.append((model_id, f"every endpoint negative ({providers})"))

    for model_id, why in suspect:
        print(f"SUSPECT {model_id}: {why} -- confirm with a real call before removing")
    for model_id, why in dead:
        print(f"DEAD {model_id}: {why}")
    if dead:
        return 1
    print(f"all {len(served)} routed models resolve; {len(suspect)} to eyeball")
    return 0


REGISTRY_PATH = (
    Path(__file__).resolve().parent.parent
    / "src" / "reasoner" / "infrastructure" / "llm" / "registry.py"
)

_MODEL_ID_RE = re.compile(r'"model":\s*"([^"]+)"')
_EXISTING_SYNCED_FIELD_RE = re.compile(r',\s*"(?:price_in|price_out|context)":\s*-?[0-9.]+')
_ENTRY_OPEN_RE = re.compile(r'^    (?:"[^"]+"|[A-Z][A-Z0-9_]*):\s*\{\s*$')
_ENTRY_CLOSE_RE = re.compile(r'^    \},?\s*$')


def _entry_spans(lines: list[str]) -> list[tuple[int, int]]:
    """One (start, end) index pair per whitelist entry, inclusive.

    A single-line entry is (i, i). A multi-line entry (an inline extra_body
    dict, or any entry whose key: { opens with nothing else on the line) runs
    from its opening `    "key": {` to the matching `    },` at the same
    4-space indent -- the convention every entry in this section already
    follows, single- or multi-line.
    """
    spans: list[tuple[int, int]] = []
    i = 0
    while i < len(lines):
        if _ENTRY_OPEN_RE.match(lines[i]):
            start = i
            j = i + 1
            while j < len(lines) and not _ENTRY_CLOSE_RE.match(lines[j]):
                j += 1
            spans.append((start, min(j, len(lines) - 1)))
            i = j + 1
        else:
            if _MODEL_ID_RE.search(lines[i]):
                spans.append((i, i))
            i += 1
    return spans


def sync_whitelist(catalogue: dict[str, Any]) -> int:
    """Rewrite registry.py's whitelist entries with price_in/price_out/context
    fields derived from the catalogue, replacing whatever a prior sync left
    there (idempotent: re-running with unchanged catalogue prices is a no-op).

    docs/plans/root-cause-remediation-2026-09-07.md P4 step 1. A price in a
    freeform comment (D9) cannot be tested; a structured field can --
    tests/unit/test_whitelist_matches_catalogue.py is the test. Comments are
    left untouched on purpose: they carry reasons, bloc-diversity flags and
    budget-pin notes a blind regex cannot tell apart from a price figure
    without risking corrupting them.

    Skips any entry whose span carries a `"base"` key (Ollama, and the one
    NVIDIA-direct NIM pin): those route to a different provider entirely, so
    an OpenRouter catalogue price would misrepresent what actually bills.
    Fails without writing anything if any other synced entry's model id is
    absent from the catalogue.
    """
    by_id = {m["id"]: m for m in catalogue.get("data", [])}
    lines = REGISTRY_PATH.read_text(encoding="utf-8").splitlines(keepends=True)
    new_lines = list(lines)

    errors: list[str] = []
    updated = 0

    for start, end in _entry_spans(lines):
        span_text = "".join(lines[start:end + 1])
        match = _MODEL_ID_RE.search(span_text)
        if not match or '"base":' in span_text:
            continue

        model_id = match.group(1).lstrip("~")
        entry = by_id.get(model_id)
        if entry is None:
            errors.append(f"{start + 1}: {model_id!r} routed but absent from the catalogue")
            continue

        fields: list[str] = []
        pricing = entry.get("pricing") or {}
        prompt_price = float(pricing["prompt"]) if "prompt" in pricing else None
        completion_price = float(pricing["completion"]) if "completion" in pricing else None
        # OpenRouter uses -1 for variable/pass-through pricing on router aliases
        # (e.g. openrouter/pareto-code): the real price depends on whichever
        # underlying model gets picked per call, so there is no fixed per-token
        # rate to sync. round(-1 * 1e6, 6) would otherwise write a nonsense
        # -1000000.0 "price".
        if prompt_price is not None and completion_price is not None and prompt_price >= 0 and completion_price >= 0:
            fields.append(f'"price_in": {round(prompt_price * 1_000_000, 6)}')
            fields.append(f'"price_out": {round(completion_price * 1_000_000, 6)}')
        if context := entry.get("context_length"):
            fields.append(f'"context": {context}')
        if not fields:
            continue

        # The "model" key's own line, wherever it falls in the span.
        line_idx = next(i for i in range(start, end + 1) if _MODEL_ID_RE.search(lines[i]))
        line = lines[line_idx]
        line_match = _MODEL_ID_RE.search(line)
        cleaned = _EXISTING_SYNCED_FIELD_RE.sub("", line)
        insert_at = cleaned.index(line_match.group(0)) + len(line_match.group(0))
        new_line = cleaned[:insert_at] + ", " + ", ".join(fields) + cleaned[insert_at:]
        if new_line != line:
            updated += 1
        new_lines[line_idx] = new_line

    if errors:
        for e in errors:
            print(f"{REGISTRY_PATH.name}:{e}", file=sys.stderr)
        print(f"\nFAIL: {len(errors)} routed model(s) absent from the catalogue.", file=sys.stderr)
        return 1

    REGISTRY_PATH.write_text("".join(new_lines), encoding="utf-8")
    print(f"synced {updated} entries")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if the bundled catalogue differs from upstream.",
    )
    parser.add_argument(
        "--check-endpoints",
        action="store_true",
        help=(
            "Do not write; exit 1 if any model the registry routes has no healthy "
            "serving endpoint. Answers a different question from --check: a model "
            "can be listed in /api/v1/models and still be unservable."
        ),
    )
    parser.add_argument(
        "--sync-whitelist",
        action="store_true",
        help=(
            "Rewrite registry.py's price_in/price_out/context fields from the "
            "bundled catalogue (not a live fetch -- keeps it offline and "
            "reproducible). Fails without writing if a routed model id is "
            "absent from the catalogue."
        ),
    )
    args = parser.parse_args()

    if args.check_endpoints:
        return check_endpoints()

    if args.sync_whitelist:
        if not OUTPUT_PATH.exists():
            print(f"MISSING: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        with OUTPUT_PATH.open("r", encoding="utf-8") as fh:
            return sync_whitelist(json.load(fh))

    catalogue = fetch_catalogue()
    live_ids = _model_ids(catalogue)

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"MISSING: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        with OUTPUT_PATH.open("r", encoding="utf-8") as fh:
            bundled_ids = _model_ids(json.load(fh))
        added, removed = live_ids - bundled_ids, bundled_ids - live_ids
        if not added and not removed:
            print(f"up to date ({len(live_ids)} models)")
            return 0
        for mid in sorted(added):
            print(f"+ {mid}")
        for mid in sorted(removed):
            print(f"- {mid}")
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as fh:
        json.dump(catalogue, fh, indent=1, sort_keys=False)
        fh.write("\n")

    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"wrote {len(live_ids)} models to {OUTPUT_PATH} ({size_kb:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
