"""JPEG C2PA / AI-provenance metadata inspection and stripping.

Fixtures are constructed byte-for-byte. The entropy-coded scan is opaque
filler bytes here -- strip()'s job is to copy it through unexamined, which
these tests verify by byte-equality, not by decoding an actual image.
"""

from __future__ import annotations

import struct

from reasoner.core.ports.watermark_port import ImageFormat
from reasoner.domain.watermark.marks import MarkConfidence
from reasoner.infrastructure.watermark.image import jpeg

SOI = b"\xff\xd8"
EOI = b"\xff\xd9"
SCAN_DATA = b"\x00\x01\x02\x03\xff\x00\x04"  # includes a stuffed 0xFF 0x00, opaque either way


def _segment(marker: int, payload: bytes = b"") -> bytes:
    seglen = len(payload) + 2
    return bytes([0xFF, marker]) + struct.pack(">H", seglen) + payload


def _sos_and_tail() -> bytes:
    return bytes([0xFF, 0xDA]) + struct.pack(">H", 2) + SCAN_DATA + EOI


def _jpeg(*segments: bytes) -> bytes:
    return SOI + b"".join(segments) + _sos_and_tail()


BASELINE_JPEG = _jpeg(_segment(0xE0, b"JFIF\x00"))  # APP0 only


class TestSupports:
    def test_valid_soi(self):
        assert jpeg.supports(BASELINE_JPEG) is True

    def test_non_jpeg_bytes(self):
        assert jpeg.supports(b"not a jpeg") is False


class TestInspectClean:
    def test_baseline_has_no_findings(self):
        report = jpeg.inspect(BASELINE_JPEG)
        assert report.format is ImageFormat.JPEG
        assert report.has_c2pa is False
        assert report.findings == ()

    def test_not_a_jpeg_reports_note(self):
        report = jpeg.inspect(b"garbage")
        assert report.notes == ("not a JPEG",)


class TestInspectApp11:
    def test_app11_segment_is_confirmed_c2pa(self):
        data = _jpeg(_segment(0xEB, b"jumbf box bytes"))
        report = jpeg.inspect(data)
        assert report.has_c2pa is True
        assert any(f.confidence is MarkConfidence.CONFIRMED for f in report.findings)


class TestInspectAppnMarkers:
    def test_app1_with_ai_hint_is_probable(self):
        data = _jpeg(_segment(0xE1, b"Exif\x00\x00Generated by Claude"))
        report = jpeg.inspect(data)
        assert report.has_ai_metadata is True
        assert any(f.confidence is MarkConfidence.PROBABLE for f in report.findings)

    def test_app1_without_ai_hint_not_flagged(self):
        data = _jpeg(_segment(0xE1, b"Exif\x00\x00just camera metadata"))
        report = jpeg.inspect(data)
        assert report.has_ai_metadata is False

    def test_app0_jfif_never_flagged(self):
        report = jpeg.inspect(BASELINE_JPEG)
        assert report.has_ai_metadata is False


class TestInspectByteScanFallback:
    def test_c2pa_substring_outside_segments_is_likely_false_positive(self):
        data = SOI + _segment(0xE0, b"JFIF\x00") + bytes([0xFF, 0xDA]) + struct.pack(">H", 2) + b"...c2pa..." + EOI
        report = jpeg.inspect(data)
        assert report.has_c2pa is True
        assert any(f.confidence is MarkConfidence.LIKELY_FALSE_POSITIVE for f in report.findings)


class TestStripApp11AlwaysDropped:
    def test_app11_dropped_even_when_not_aggressive(self):
        data = _jpeg(_segment(0xEB, b"jumbf"))
        cleaned, actions = jpeg.strip(data, strip_all_metadata=False)
        assert b"jumbf" not in cleaned
        assert any("APP11" in a for a in actions)

    def test_stripped_reinspects_clean(self):
        data = _jpeg(_segment(0xEB, b"jumbf"), _segment(0xE1, b"Exif\x00\x00Claude"))
        cleaned, _actions = jpeg.strip(data)
        report = jpeg.inspect(cleaned)
        assert report.has_c2pa is False
        assert report.has_ai_metadata is False


class TestStripApp0Preserved:
    def test_app0_jfif_survives_aggressive_strip(self):
        cleaned, _actions = jpeg.strip(BASELINE_JPEG, strip_all_metadata=True)
        assert b"JFIF" in cleaned


class TestStripAggressiveVsConservative:
    def test_aggressive_drops_benign_app1(self):
        data = _jpeg(_segment(0xE1, b"Exif\x00\x00benign camera data"))
        cleaned, _actions = jpeg.strip(data, strip_all_metadata=True)
        assert b"benign camera data" not in cleaned

    def test_conservative_keeps_benign_app1(self):
        data = _jpeg(_segment(0xE1, b"Exif\x00\x00benign camera data"))
        cleaned, _actions = jpeg.strip(data, strip_all_metadata=False)
        assert b"benign camera data" in cleaned

    def test_conservative_still_drops_ai_marked_app1(self):
        data = _jpeg(_segment(0xE1, b"Exif\x00\x00Generated by Claude"))
        cleaned, actions = jpeg.strip(data, strip_all_metadata=False)
        assert b"Claude" not in cleaned
        assert any("AI/C2PA" in a for a in actions)


class TestStripComComment:
    def test_com_segment_always_dropped(self):
        data = _jpeg(_segment(0xFE, b"a plain comment"))
        cleaned, actions = jpeg.strip(data, strip_all_metadata=False)
        assert b"a plain comment" not in cleaned
        assert any("COM" in a for a in actions)


class TestStripPreservesEntropyScan:
    def test_scan_data_byte_identical(self):
        data = _jpeg(_segment(0xEB, b"jumbf"))
        cleaned, actions = jpeg.strip(data)
        assert SCAN_DATA in cleaned
        assert cleaned.endswith(SCAN_DATA + EOI)
        assert any("entropy-coded scan" in a for a in actions)

    def test_starts_with_soi_ends_with_eoi(self):
        cleaned, _actions = jpeg.strip(BASELINE_JPEG)
        assert cleaned.startswith(SOI)
        assert cleaned.endswith(EOI)


class TestStripIdempotent:
    def test_clean_jpeg_reports_no_dropped_segments(self):
        # The SOS branch always logs "preserved entropy-coded scan" once
        # reached, so the "no JPEG APP segments removed" fallback text only
        # ever appears for a JPEG that never reaches SOS at all (e.g.
        # truncated before the scan) -- not exercised by a normal clean file.
        _cleaned, actions = jpeg.strip(BASELINE_JPEG)
        assert "drop" not in " ".join(actions)
        assert "preserved entropy-coded scan (SOS->EOF)" in actions

    def test_strip_twice_stable(self):
        data = _jpeg(_segment(0xEB, b"jumbf"), _segment(0xE1, b"Exif\x00\x00Claude"))
        once, _ = jpeg.strip(data)
        twice, actions_twice = jpeg.strip(once)
        assert once == twice
        assert "drop" not in " ".join(actions_twice)
