"""AVIF/HEIC C2PA / AI-provenance metadata inspection and stripping.

Fixtures are minimal ISOBMFF box trees, constructed byte-for-byte.
"""

from __future__ import annotations

import struct

import pytest

from reasoner.core.ports.watermark_port import ImageFormat
from reasoner.domain.watermark.marks import MarkConfidence
from reasoner.infrastructure.watermark.image import isobmff


def _box(fourcc: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", len(payload) + 8) + fourcc + payload


def _ftyp(brand: bytes) -> bytes:
    payload = brand + b"\x00\x00\x00\x00" + brand
    return _box(b"ftyp", payload)


def _meta_box(*sub_boxes: bytes) -> bytes:
    payload = b"\x00\x00\x00\x00" + b"".join(sub_boxes)  # version+flags, then sub-boxes
    return _box(b"meta", payload)


def _avif(*top_level_boxes: bytes) -> bytes:
    return _ftyp(b"avif") + b"".join(top_level_boxes)


def _heic(*top_level_boxes: bytes) -> bytes:
    return _ftyp(b"heic") + b"".join(top_level_boxes)


MDAT_BOX = _box(b"mdat", b"\x00\x01\x02\x03pixeldata")
BASELINE_AVIF = _avif(_meta_box(_box(b"hdlr", b"handler stuff")), MDAT_BOX)


class TestSupports:
    def test_avif_brand(self):
        assert isobmff.supports(_avif()) is True

    def test_heic_brand(self):
        assert isobmff.supports(_heic()) is True

    def test_non_isobmff(self):
        assert isobmff.supports(b"not isobmff") is False

    def test_png_is_not_supported(self):
        assert isobmff.supports(b"\x89PNG\r\n\x1a\n" + b"\x00" * 20) is False


class TestInspectClean:
    def test_baseline_has_no_findings(self):
        report = isobmff.inspect(BASELINE_AVIF)
        assert report.format is ImageFormat.AVIF
        assert report.has_c2pa is False
        assert report.findings == ()

    def test_malformed_reports_note(self):
        report = isobmff.inspect(b"not a valid container")
        assert report.has_c2pa is False
        assert report.notes


class TestInspectTopLevelC2pa:
    def test_top_level_jumb_box_confirmed(self):
        data = _avif(_box(b"jumb", b"jumbf manifest bytes"), MDAT_BOX)
        report = isobmff.inspect(data)
        assert report.has_c2pa is True
        assert any(f.confidence is MarkConfidence.CONFIRMED for f in report.findings)

    def test_top_level_c2pa_prefixed_box_confirmed(self):
        data = _avif(_box(b"c2ma", b"c2pa related box"), MDAT_BOX)
        report = isobmff.inspect(data)
        assert report.has_c2pa is True


class TestInspectXmpUuidBox:
    def test_xmp_uuid_box_is_informational(self):
        data = _avif(_box(b"uuid", isobmff.XMP_UUID + b"<xmp packet bytes>"), MDAT_BOX)
        report = isobmff.inspect(data)
        assert report.has_ai_metadata is True
        assert any(f.confidence is MarkConfidence.INFORMATIONAL for f in report.findings)

    def test_non_xmp_uuid_with_ai_hint_is_probable(self):
        data = _avif(_box(b"uuid", b"\x00" * 16 + b"Generated by Claude"), MDAT_BOX)
        report = isobmff.inspect(data)
        assert report.has_ai_metadata is True
        assert any(f.confidence is MarkConfidence.PROBABLE for f in report.findings)

    def test_non_xmp_uuid_without_hint_not_flagged(self):
        data = _avif(_box(b"uuid", b"\x00" * 16 + b"vendor-specific opaque data"), MDAT_BOX)
        report = isobmff.inspect(data)
        assert report.has_ai_metadata is False


class TestInspectMetaSubBoxes:
    def test_meta_sub_box_jumb_confirmed(self):
        data = _avif(_meta_box(_box(b"jumb", b"jumbf")), MDAT_BOX)
        report = isobmff.inspect(data)
        assert report.has_c2pa is True

    def test_meta_sub_box_xml_with_ai_hint_probable(self):
        data = _avif(_meta_box(_box(b"xml ", b"<xmp>Generated by Claude</xmp>")), MDAT_BOX)
        report = isobmff.inspect(data)
        assert report.has_ai_metadata is True


class TestStripTopLevelC2pa:
    def test_jumb_box_dropped(self):
        data = _avif(_box(b"jumb", b"jumbf manifest"), MDAT_BOX)
        cleaned, actions = isobmff.strip(data)
        assert b"jumbf manifest" not in cleaned
        assert any("C2PA" in a for a in actions)

    def test_mdat_survives(self):
        data = _avif(_box(b"jumb", b"jumbf manifest"), MDAT_BOX)
        cleaned, _actions = isobmff.strip(data)
        assert b"pixeldata" in cleaned

    def test_stripped_reinspects_clean(self):
        data = _avif(
            _box(b"jumb", b"jumbf manifest"),
            _box(b"uuid", isobmff.XMP_UUID + b"xmp packet"),
            MDAT_BOX,
        )
        cleaned, _actions = isobmff.strip(data)
        report = isobmff.inspect(cleaned)
        assert report.has_c2pa is False
        assert report.has_ai_metadata is False


class TestStripMetaSubBoxes:
    def test_meta_sub_box_c2pa_dropped_but_meta_box_survives(self):
        data = _avif(_meta_box(_box(b"hdlr", b"handler"), _box(b"jumb", b"jumbf")), MDAT_BOX)
        cleaned, actions = isobmff.strip(data)
        assert b"jumbf" not in cleaned
        assert b"handler" in cleaned  # benign sub-box under conservative default kept... see below
        assert any("meta sub-box" in a for a in actions)


class TestStripAggressiveVsConservative:
    def test_conservative_keeps_benign_uuid(self):
        data = _avif(_box(b"uuid", b"\x00" * 16 + b"benign vendor data"), MDAT_BOX)
        cleaned, _actions = isobmff.strip(data, strip_all_metadata=False)
        assert b"benign vendor data" in cleaned

    def test_aggressive_drops_benign_uuid(self):
        data = _avif(_box(b"uuid", b"\x00" * 16 + b"benign vendor data"), MDAT_BOX)
        cleaned, _actions = isobmff.strip(data, strip_all_metadata=True)
        assert b"benign vendor data" not in cleaned

    def test_conservative_still_drops_ai_marked_uuid(self):
        data = _avif(_box(b"uuid", b"\x00" * 16 + b"Generated by Claude"), MDAT_BOX)
        cleaned, actions = isobmff.strip(data, strip_all_metadata=False)
        assert b"Claude" not in cleaned
        assert any("UUID metadata" in a for a in actions)


class TestStripMalformedRaises:
    def test_no_boxes_raises(self):
        with pytest.raises(ValueError, match="not a valid"):
            isobmff.strip(b"not isobmff data at all, no boxes here")


class TestStripIdempotent:
    def test_clean_avif_reports_no_op(self):
        _cleaned, actions = isobmff.strip(BASELINE_AVIF)
        assert actions == ("no AVIF metadata boxes removed (already clean or none matched)",)

    def test_strip_twice_stable(self):
        data = _avif(_box(b"jumb", b"jumbf manifest"), MDAT_BOX)
        once, _ = isobmff.strip(data)
        twice, actions_twice = isobmff.strip(once)
        assert once == twice
        assert actions_twice == ("no AVIF metadata boxes removed (already clean or none matched)",)


class TestHeicFormatLabel:
    def test_heic_reports_heic_format(self):
        report = isobmff.inspect(_heic(_box(b"jumb", b"jumbf")))
        assert report.format is ImageFormat.HEIC
