"""PNG C2PA / AI-provenance metadata inspection and stripping.

Fixtures are constructed byte-for-byte (not sourced from real files) since
the scrubber never validates pixel data or CRCs -- only chunk type, length,
and text-chunk payload content matter to it. Round-trip assertions confirm
strip() output re-inspects clean, matching the reference project's
inspect-predicts-clean guarantee for the image class.
"""

from __future__ import annotations

import struct

from reasoner.core.ports.watermark_port import ImageFormat
from reasoner.domain.watermark.marks import MarkConfidence
from reasoner.infrastructure.watermark.image import png

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
_DUMMY_CRC = b"\x00\x00\x00\x00"  # never validated by this scrubber, only copied through
MINIMAL_IHDR_PAYLOAD = struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0)  # 1x1, 8-bit truecolor


def _chunk(ctype: bytes, payload: bytes = b"") -> bytes:
    return struct.pack(">I", len(payload)) + ctype + payload + _DUMMY_CRC


def _png(*extra_chunks: bytes) -> bytes:
    return (
        PNG_SIGNATURE
        + _chunk(b"IHDR", MINIMAL_IHDR_PAYLOAD)
        + b"".join(extra_chunks)
        + _chunk(b"IDAT", b"\x00")
        + _chunk(b"IEND")
    )


BASELINE_PNG = _png()


class TestSupports:
    def test_valid_png_signature(self):
        assert png.supports(BASELINE_PNG) is True

    def test_non_png_bytes(self):
        assert png.supports(b"not a png at all") is False

    def test_empty_bytes(self):
        assert png.supports(b"") is False


class TestInspectClean:
    def test_baseline_png_has_no_findings(self):
        report = png.inspect(BASELINE_PNG)
        assert report.format is ImageFormat.PNG
        assert report.has_c2pa is False
        assert report.has_ai_metadata is False
        assert report.findings == ()

    def test_not_a_png_reports_note(self):
        report = png.inspect(b"garbage")
        assert report.notes == ("not a PNG",)


class TestInspectC2paChunk:
    def test_cabx_chunk_detected_as_c2pa(self):
        data = _png(_chunk(b"caBX", b"c2pa manifest bytes"))
        report = png.inspect(data)
        assert report.has_c2pa is True
        assert report.has_ai_metadata is True
        assert any(f.confidence is MarkConfidence.CONFIRMED for f in report.findings)

    def test_jumb_chunk_detected_as_c2pa(self):
        data = _png(_chunk(b"jumb", b"jumbf box"))
        report = png.inspect(data)
        assert report.has_c2pa is True


class TestInspectTextChunkMarkers:
    def test_text_chunk_with_ai_hint_is_probable(self):
        data = _png(_chunk(b"tEXt", b"Software\x00Generated by Claude"))
        report = png.inspect(data)
        assert report.has_ai_metadata is True
        assert any(f.confidence is MarkConfidence.PROBABLE for f in report.findings)

    def test_text_chunk_with_c2pa_hint_sets_has_c2pa(self):
        data = _png(_chunk(b"iTXt", b"xmp\x00...contentcredentials..."))
        report = png.inspect(data)
        assert report.has_c2pa is True

    def test_text_chunk_without_markers_is_not_flagged(self):
        data = _png(_chunk(b"tEXt", b"Comment\x00just a normal comment"))
        report = png.inspect(data)
        assert report.has_ai_metadata is False
        assert report.findings == ()


class TestInspectByteScanFallback:
    def test_c2pa_marker_outside_recognized_chunk_is_likely_false_positive(self):
        # A "c2pa" substring inside IDAT (compressed pixel data in reality,
        # here just opaque bytes) is a byte-scan hit, not a parsed structure.
        data = _png(_chunk(b"IDAT", b"...c2pa..."))
        report = png.inspect(data)
        assert report.has_c2pa is True
        assert any(f.confidence is MarkConfidence.LIKELY_FALSE_POSITIVE for f in report.findings)


class TestInspectTruncated:
    def test_truncated_chunk_stops_parsing_without_crashing(self):
        data = PNG_SIGNATURE + _chunk(b"IHDR", MINIMAL_IHDR_PAYLOAD) + struct.pack(">I", 9999) + b"tEXt" + b"short"
        report = png.inspect(data)
        assert report.notes  # some note about truncation, no exception raised


class TestStripRemovesC2pa:
    def test_cabx_chunk_is_dropped(self):
        data = _png(_chunk(b"caBX", b"c2pa manifest"))
        cleaned, actions = png.strip(data)
        assert b"caBX" not in cleaned
        assert any("C2PA" in a for a in actions)

    def test_stripped_png_reinspects_clean(self):
        data = _png(_chunk(b"caBX", b"c2pa manifest"), _chunk(b"tEXt", b"Software\x00Claude"))
        cleaned, _actions = png.strip(data)
        report = png.inspect(cleaned)
        assert report.has_c2pa is False
        assert report.has_ai_metadata is False


class TestStripAggressiveVsConservative:
    def test_aggressive_drops_all_text_chunks(self):
        data = _png(_chunk(b"tEXt", b"Comment\x00totally benign"))
        cleaned, actions = png.strip(data, strip_all_metadata=True)
        assert b"tEXt" not in cleaned
        assert actions

    def test_conservative_keeps_benign_text_chunks(self):
        data = _png(_chunk(b"tEXt", b"Comment\x00totally benign"))
        cleaned, _actions = png.strip(data, strip_all_metadata=False)
        assert b"tEXt" in cleaned

    def test_conservative_still_drops_ai_marked_text_chunks(self):
        data = _png(_chunk(b"tEXt", b"Software\x00Generated by Claude"))
        cleaned, actions = png.strip(data, strip_all_metadata=False)
        assert b"tEXt" not in cleaned
        assert any("AI/C2PA" in a for a in actions)


class TestStripPreservesStructure:
    def test_ihdr_idat_iend_survive(self):
        data = _png(_chunk(b"caBX", b"c2pa"))
        cleaned, _actions = png.strip(data)
        assert cleaned.startswith(PNG_SIGNATURE)
        assert b"IHDR" in cleaned
        assert b"IDAT" in cleaned
        assert cleaned.endswith(b"IEND" + _DUMMY_CRC)

    def test_clean_png_reports_no_op_action(self):
        _cleaned, actions = png.strip(BASELINE_PNG)
        assert actions == ("no PNG metadata chunks removed (already clean or none matched)",)

    def test_strip_is_idempotent(self):
        data = _png(_chunk(b"caBX", b"c2pa"), _chunk(b"tEXt", b"Software\x00Claude"))
        once, _ = png.strip(data)
        twice, actions_twice = png.strip(once)
        assert once == twice
        assert actions_twice == ("no PNG metadata chunks removed (already clean or none matched)",)
