"""WebP C2PA / AI-provenance metadata inspection and stripping.

The VP8X-feature-flag fixup is the behavior most worth pinning: dropping an
ICCP/EXIF/XMP chunk without clearing the matching bit in VP8X's flags byte
produces a file that declares metadata it no longer has.
"""

from __future__ import annotations

import struct

from reasoner.core.ports.watermark_port import ImageFormat
from reasoner.domain.watermark.marks import MarkConfidence
from reasoner.infrastructure.watermark.image import webp

WEBP_RIFF = b"RIFF"
WEBP_SIG = b"WEBP"

ICCP_BIT, EXIF_BIT, XMP_BIT = 0x20, 0x08, 0x04


def _riff_chunk(fourcc: bytes, payload: bytes) -> bytes:
    padding = b"\x00" if len(payload) & 1 else b""
    return fourcc + struct.pack("<I", len(payload)) + payload + padding


def _webp(*chunks: bytes) -> bytes:
    body = WEBP_SIG + b"".join(chunks)
    return WEBP_RIFF + struct.pack("<I", len(body)) + body


def _vp8x_payload(flags: int) -> bytes:
    return bytes([flags]) + b"\x00" * 9  # 3 reserved + 3 width-1 + 3 height-1, all zero


def _vp8x_flags(payload: bytes) -> int:
    return payload[0]


BASELINE_WEBP = _webp(_riff_chunk(b"VP8 ", b"\x00\x01\x02\x03"))


class TestSupports:
    def test_valid_webp(self):
        assert webp.supports(BASELINE_WEBP) is True

    def test_non_webp_riff(self):
        data = b"RIFF" + struct.pack("<I", 4) + b"WAVE"
        assert webp.supports(data) is False

    def test_non_riff_bytes(self):
        assert webp.supports(b"not webp at all") is False


class TestInspectClean:
    def test_baseline_has_no_findings(self):
        report = webp.inspect(BASELINE_WEBP)
        assert report.format is ImageFormat.WEBP
        assert report.has_c2pa is False
        assert report.findings == ()

    def test_not_webp_reports_note(self):
        report = webp.inspect(b"garbage")
        assert report.notes == ("not a WebP",)


class TestInspectC2paChunk:
    def test_c2pa_chunk_confirmed(self):
        data = _webp(_riff_chunk(b"VP8 ", b"\x00"), _riff_chunk(b"C2PA", b"manifest bytes"))
        report = webp.inspect(data)
        assert report.has_c2pa is True
        assert any(f.confidence is MarkConfidence.CONFIRMED for f in report.findings)


class TestInspectXmpExifMarkers:
    def test_xmp_with_ai_hint_is_probable(self):
        vp8x = _vp8x_payload(XMP_BIT)
        data = _webp(
            _riff_chunk(b"VP8X", vp8x),
            _riff_chunk(b"XMP ", b"Generated by Claude"),
            _riff_chunk(b"VP8 ", b"\x00"),
        )
        report = webp.inspect(data)
        assert report.has_ai_metadata is True
        assert any(f.confidence is MarkConfidence.PROBABLE for f in report.findings)

    def test_exif_without_hint_not_flagged(self):
        vp8x = _vp8x_payload(EXIF_BIT)
        data = _webp(_riff_chunk(b"VP8X", vp8x), _riff_chunk(b"EXIF", b"plain camera data"))
        report = webp.inspect(data)
        assert report.has_ai_metadata is False


class TestStripC2pa:
    def test_c2pa_chunk_dropped(self):
        data = _webp(_riff_chunk(b"VP8 ", b"\x00"), _riff_chunk(b"C2PA", b"manifest"))
        cleaned, actions = webp.strip(data)
        assert b"manifest" not in cleaned
        assert any("C2PA" in a for a in actions)

    def test_stripped_reinspects_clean(self):
        data = _webp(_riff_chunk(b"VP8 ", b"\x00"), _riff_chunk(b"C2PA", b"manifest"))
        cleaned, _actions = webp.strip(data)
        report = webp.inspect(cleaned)
        assert report.has_c2pa is False


class TestStripVp8xFlagFixup:
    def test_dropped_metadata_clears_vp8x_flags(self):
        vp8x = _vp8x_payload(ICCP_BIT | EXIF_BIT | XMP_BIT)
        data = _webp(
            _riff_chunk(b"VP8X", vp8x),
            _riff_chunk(b"ICCP", b"color profile"),
            _riff_chunk(b"EXIF", b"camera data"),
            _riff_chunk(b"XMP ", b"xmp packet"),
            _riff_chunk(b"VP8 ", b"\x00"),
        )
        cleaned, _actions = webp.strip(data, strip_all_metadata=True)
        chunks, _notes = webp._walk_chunks(cleaned)
        vp8x_chunks = [payload for fourcc, payload, _pad in chunks if fourcc == b"VP8X"]
        assert len(vp8x_chunks) == 1
        assert _vp8x_flags(vp8x_chunks[0]) == 0  # all three bits cleared
        assert b"color profile" not in cleaned
        assert b"camera data" not in cleaned
        assert b"xmp packet" not in cleaned

    def test_partial_drop_clears_only_the_dropped_bit(self):
        # Conservative mode: only the AI-marked XMP chunk is dropped; ICCP
        # (benign) survives, and only XMP's bit should clear.
        vp8x = _vp8x_payload(ICCP_BIT | XMP_BIT)
        data = _webp(
            _riff_chunk(b"VP8X", vp8x),
            _riff_chunk(b"ICCP", b"color profile"),
            _riff_chunk(b"XMP ", b"Generated by Claude"),
            _riff_chunk(b"VP8 ", b"\x00"),
        )
        cleaned, _actions = webp.strip(data, strip_all_metadata=False)
        chunks, _notes = webp._walk_chunks(cleaned)
        vp8x_payload = next(payload for fourcc, payload, _pad in chunks if fourcc == b"VP8X")
        assert _vp8x_flags(vp8x_payload) == ICCP_BIT  # XMP bit cleared, ICCP bit kept
        assert b"color profile" in cleaned
        assert b"Claude" not in cleaned


class TestStripAggressiveVsConservative:
    def test_conservative_keeps_benign_metadata(self):
        vp8x = _vp8x_payload(EXIF_BIT)
        data = _webp(_riff_chunk(b"VP8X", vp8x), _riff_chunk(b"EXIF", b"benign camera data"))
        cleaned, _actions = webp.strip(data, strip_all_metadata=False)
        assert b"benign camera data" in cleaned

    def test_aggressive_drops_benign_metadata(self):
        vp8x = _vp8x_payload(EXIF_BIT)
        data = _webp(_riff_chunk(b"VP8X", vp8x), _riff_chunk(b"EXIF", b"benign camera data"))
        cleaned, _actions = webp.strip(data, strip_all_metadata=True)
        assert b"benign camera data" not in cleaned


class TestStripMalformedRaises:
    def test_not_webp_raises(self):
        import pytest

        with pytest.raises(ValueError, match="not WebP"):
            webp.strip(b"garbage")

    def test_truncated_chunk_raises(self):
        import pytest

        # VP8X chunk declares more payload than actually present.
        truncated = WEBP_RIFF + struct.pack("<I", 20) + WEBP_SIG + b"VP8X" + struct.pack("<I", 999) + b"short"
        with pytest.raises(ValueError, match="malformed WebP"):
            webp.strip(truncated)


class TestStripIdempotent:
    def test_clean_webp_reports_no_op(self):
        _cleaned, actions = webp.strip(BASELINE_WEBP)
        assert actions == ("no WebP metadata chunks removed (already clean or none matched)",)

    def test_strip_twice_stable(self):
        data = _webp(_riff_chunk(b"VP8 ", b"\x00"), _riff_chunk(b"C2PA", b"manifest"))
        once, _ = webp.strip(data)
        twice, actions_twice = webp.strip(once)
        assert once == twice
        assert actions_twice == ("no WebP metadata chunks removed (already clean or none matched)",)
